using MediatR;
using Microsoft.EntityFrameworkCore;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;

namespace Qseng.Application.Relationships.DeleteRelationship;

public record DeleteRelationshipCommand(Guid Id) : IRequest<Result<bool>>;

public class DeleteRelationshipHandler : IRequestHandler<DeleteRelationshipCommand, Result<bool>>
{
    private readonly IQsengDbContext _db;
    public DeleteRelationshipHandler(IQsengDbContext db) => _db = db;

    public async Task<Result<bool>> Handle(DeleteRelationshipCommand cmd, CancellationToken ct)
    {
        var rel = await _db.Relationships.FindAsync([cmd.Id], ct);
        if (rel is null) return Result<bool>.NotFound("Relationship not found.");

        // Clean up auto-generated events linked to this relationship
        var autoEvents = await _db.TimelineEvents
            .Where(e => e.SourceRelationshipId == cmd.Id && e.IsAutoGenerated)
            .ToListAsync(ct);
        _db.TimelineEvents.RemoveRange(autoEvents);

        _db.Relationships.Remove(rel);
        await _db.SaveChangesAsync(ct);
        return Result<bool>.Ok(true);
    }
}
