services:
  api:
    depends_on: !reset []
    environment:
      DB_PROVIDER: sqlite
      CONNECTION_STRING: "Data Source=/data/qseng.db"
      ASPNETCORE_ENVIRONMENT: Development
      Uploads__Path: /app/uploads
    volumes:
      - sqlitedata:/data
      - uploads:/app/uploads
    build:
      args:
        - ASPNETCORE_ENVIRONMENT=Development
  postgres:
    profiles: ["disabled"]

volumes:
  sqlitedata:
  uploads:
