using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;
using Qseng.Domain.Entities;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Application.Relationships.CreateRelationship;

public record CreateRelationshipCommand(
    Guid TreeId, Guid FromPersonId, Guid ToPersonId, RelationshipType Type,
    int? StartYear, int? StartMonth, int? StartDay,
    int? EndYear, int? EndMonth, int? EndDay,
    string? Notes)
    : IRequest<Result<RelationshipDto>>;

public class CreateRelationshipValidator : AbstractValidator<CreateRelationshipCommand>
{
    public CreateRelationshipValidator()
    {
        RuleFor(x => x.FromPersonId).NotEmpty();
        RuleFor(x => x.ToPersonId).NotEmpty();
        RuleFor(x => x.FromPersonId).NotEqual(x => x.ToPersonId).WithMessage("Cannot relate a person to themselves.");
    }
}

public class CreateRelationshipHandler : IRequestHandler<CreateRelationshipCommand, Result<RelationshipDto>>
{
    private readonly IQsengDbContext _db;
    private readonly ICurrentUser _currentUser;

    public CreateRelationshipHandler(IQsengDbContext db, ICurrentUser currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<Result<RelationshipDto>> Handle(CreateRelationshipCommand cmd, CancellationToken ct)
    {
        var tree = await _db.Trees.FindAsync([cmd.TreeId], ct);
        if (tree is null) return Result<RelationshipDto>.NotFound("Tree not found.");
        if (tree.OwnerId != _currentUser.UserId) return Result<RelationshipDto>.Fail("Forbidden.", 403);

        var personIds = new[] { cmd.FromPersonId, cmd.ToPersonId };
        var personsInTree = await _db.Persons
            .CountAsync(p => p.TreeId == cmd.TreeId && personIds.Contains(p.Id), ct);
        if (personsInTree != 2)
            return Result<RelationshipDto>.NotFound("Person not found in this tree.");

        var duplicate = await _db.Relationships.AnyAsync(r =>
            r.TreeId == cmd.TreeId &&
            r.FromPersonId == cmd.FromPersonId &&
            r.ToPersonId == cmd.ToPersonId &&
            r.Type == cmd.Type, ct);
        if (duplicate) return Result<RelationshipDto>.Conflict("Relationship already exists.");

        if (cmd.Type == RelationshipType.Parent &&
            await RelationshipRules.WouldCreateCycleAsync(_db, cmd.TreeId, cmd.FromPersonId, cmd.ToPersonId, ct))
            return Result<RelationshipDto>.Conflict("Adding this relationship would create a cycle in the family tree.");

        var rel = new Relationship
        {
            TreeId = cmd.TreeId, FromPersonId = cmd.FromPersonId, ToPersonId = cmd.ToPersonId,
            Type = cmd.Type,
            StartYear = cmd.StartYear, StartMonth = cmd.StartMonth, StartDay = cmd.StartDay,
            EndYear = cmd.EndYear, EndMonth = cmd.EndMonth, EndDay = cmd.EndDay,
            Notes = cmd.Notes
        };
        _db.Relationships.Add(rel);

        // Auto-generate timeline events
        await GenerateTimelineEventsAsync(rel, ct);

        await _db.SaveChangesAsync(ct);
        return Result<RelationshipDto>.Ok(ToDto(rel));
    }

    private async Task GenerateTimelineEventsAsync(Relationship rel, CancellationToken ct)
    {
        switch (rel.Type)
        {
            case RelationshipType.Spouse:
                var fromPerson = await _db.Persons.FirstOrDefaultAsync(p => p.Id == rel.FromPersonId, ct);
                var toPerson   = await _db.Persons.FirstOrDefaultAsync(p => p.Id == rel.ToPersonId,   ct);
                AddMarriage(rel.FromPersonId, rel, toPerson);
                AddMarriage(rel.ToPersonId,   rel, fromPerson);
                break;
            case RelationshipType.Parent:
                var child = await _db.Persons.FirstOrDefaultAsync(p => p.Id == rel.ToPersonId, ct);
                if (child?.Birth is not null)
                {
                    _db.TimelineEvents.Add(new TimelineEvent
                    {
                        PersonId = rel.FromPersonId,
                        Type = TimelineEventType.Custom,
                        Title = $"Kind geboren: {child.FirstName} {child.LastName}",
                        Start = child.Birth,
                        IsAutoGenerated = true,
                        SourceRelationshipId = rel.Id
                    });
                }
                break;
        }
    }

    private void AddMarriage(Guid personId, Relationship r, Domain.Entities.Person? spouse)
    {
        var spouseName = spouse is not null ? $"{spouse.FirstName} {spouse.LastName}" : null;
        var title = spouseName is not null ? $"Hochzeit mit {spouseName}" : "Hochzeit";
        _db.TimelineEvents.Add(new TimelineEvent
        {
            PersonId = personId, Type = TimelineEventType.Marriage, Title = title,
            Start    = r.StartYear is null ? null : new PartialDate(r.StartYear, r.StartMonth, r.StartDay),
            End      = r.EndYear   is null ? null : new PartialDate(r.EndYear,   r.EndMonth,   r.EndDay),
            Location = r.Notes,
            IsAutoGenerated = true, SourceRelationshipId = r.Id
        });
    }

    internal static RelationshipDto ToDto(Relationship r) => new(
        r.Id, r.TreeId, r.FromPersonId, r.ToPersonId, r.Type,
        r.StartYear, r.StartMonth, r.StartDay,
        r.EndYear, r.EndMonth, r.EndDay, r.Notes);
}
