// GENERATED by scripts/gen-i18n-keys.mjs from public/assets/i18n/en.json. Do not edit.
export type TranslationKey =
  | 'add'
  | 'admin.action.activate'
  | 'admin.action.deactivate'
  | 'admin.action.delete'
  | 'admin.action.makeAdmin'
  | 'admin.action.password'
  | 'admin.action.removeAdmin'
  | 'admin.actions'
  | 'admin.confirm.delete'
  | 'admin.confirm.makeAdmin'
  | 'admin.confirm.removeAdmin'
  | 'admin.create.btn'
  | 'admin.create.cancel'
  | 'admin.create.displayName'
  | 'admin.create.email'
  | 'admin.create.isAdmin'
  | 'admin.create.password'
  | 'admin.create.submit'
  | 'admin.create.submitting'
  | 'admin.create.title'
  | 'admin.create.username'
  | 'admin.created.toast'
  | 'admin.deleted.toast'
  | 'admin.err.load'
  | 'admin.loading'
  | 'admin.me'
  | 'admin.pw.cancel'
  | 'admin.pw.placeholder'
  | 'admin.pw.save'
  | 'admin.pw.saved'
  | 'admin.pw.saving'
  | 'admin.pw.title'
  | 'admin.reg.hint'
  | 'admin.reg.off'
  | 'admin.reg.on'
  | 'admin.registered'
  | 'admin.registration'
  | 'admin.role.admin'
  | 'admin.role.user'
  | 'admin.saved.toast'
  | 'admin.status.active'
  | 'admin.status.inactive'
  | 'admin.table.actions'
  | 'admin.table.email'
  | 'admin.table.lang'
  | 'admin.table.registered'
  | 'admin.table.role'
  | 'admin.table.status'
  | 'admin.table.user'
  | 'admin.title'
  | 'auth.hidePassword'
  | 'auth.language'
  | 'auth.showPassword'
  | 'back'
  | 'cancel'
  | 'date.clear'
  | 'date.hint'
  | 'date.invalid'
  | 'date.pick'
  | 'date.unknown'
  | 'delete'
  | 'edit'
  | 'err.delete'
  | 'err.forbidden'
  | 'err.load'
  | 'err.save'
  | 'err.server'
  | 'event.birth'
  | 'event.custom'
  | 'event.death'
  | 'event.education'
  | 'event.marriage'
  | 'event.move'
  | 'event.occupation'
  | 'fam.add'
  | 'fam.addBtn'
  | 'fam.adoptive'
  | 'fam.adoptive.hint'
  | 'fam.adoptiveChildren'
  | 'fam.adoptiveParents'
  | 'fam.cancel'
  | 'fam.child.hint'
  | 'fam.children'
  | 'fam.date'
  | 'fam.day'
  | 'fam.month'
  | 'fam.noRels'
  | 'fam.parent.hint'
  | 'fam.parents'
  | 'fam.place'
  | 'fam.placePlaceholder'
  | 'fam.placeholder'
  | 'fam.remove'
  | 'fam.removeConfirm'
  | 'fam.search'
  | 'fam.spouse.hint'
  | 'fam.spouses'
  | 'fam.title'
  | 'fam.type'
  | 'fam.year'
  | 'form.email'
  | 'form.invalid'
  | 'form.maxlength'
  | 'form.minlength'
  | 'form.range'
  | 'form.required'
  | 'import.analyzing'
  | 'import.back'
  | 'import.commit'
  | 'import.done'
  | 'import.doneTitle'
  | 'import.err'
  | 'import.guide'
  | 'import.importing'
  | 'import.paste'
  | 'import.persons'
  | 'import.preview'
  | 'import.previewTitle'
  | 'import.rels'
  | 'import.title'
  | 'loading'
  | 'login.demo'
  | 'login.demoFill'
  | 'login.demoPass'
  | 'login.demoUser'
  | 'login.error'
  | 'login.noAccount'
  | 'login.password'
  | 'login.register'
  | 'login.submit'
  | 'login.submitting'
  | 'login.tagline'
  | 'login.title'
  | 'login.username'
  | 'media.add'
  | 'media.avatarBadge'
  | 'media.deleteConfirm'
  | 'media.empty'
  | 'media.setAvatar'
  | 'media.title'
  | 'media.uploading'
  | 'nav.lang'
  | 'nav.logout'
  | 'nav.settings'
  | 'nav.skip'
  | 'nav.theme.auto'
  | 'nav.theme.dark'
  | 'nav.theme.light'
  | 'nav.users'
  | 'optional'
  | 'pd.back'
  | 'pd.birth'
  | 'pd.causeOfDeath'
  | 'pd.death'
  | 'pd.edit'
  | 'pd.lifespan.b'
  | 'pd.lifespan.d'
  | 'pd.maiden'
  | 'pd.notes'
  | 'pd.tab.media'
  | 'pd.tab.timeline'
  | 'pe.approx'
  | 'pe.avatar'
  | 'pe.avatarHint'
  | 'pe.avatarPending'
  | 'pe.basics'
  | 'pe.birth'
  | 'pe.birthDay'
  | 'pe.birthMonth'
  | 'pe.birthPlace'
  | 'pe.birthYear'
  | 'pe.causeOfDeath'
  | 'pe.death'
  | 'pe.deathPlace'
  | 'pe.deleteConfirm'
  | 'pe.edit'
  | 'pe.firstName'
  | 'pe.lastName'
  | 'pe.maidenName'
  | 'pe.new'
  | 'pe.notes'
  | 'pe.optional'
  | 'pe.required'
  | 'pe.save'
  | 'pe.update'
  | 'register.displayName'
  | 'register.email'
  | 'register.error'
  | 'register.haveAccount'
  | 'register.login'
  | 'register.password'
  | 'register.passwordHint'
  | 'register.pendingHint'
  | 'register.pendingTitle'
  | 'register.submit'
  | 'register.submitting'
  | 'register.tagline'
  | 'register.title'
  | 'register.username'
  | 'rel.added.toast'
  | 'rel.adoptive'
  | 'rel.child'
  | 'rel.dialog.date'
  | 'rel.dialog.from'
  | 'rel.dialog.person'
  | 'rel.dialog.place'
  | 'rel.dialog.roleHint'
  | 'rel.dialog.submit'
  | 'rel.dialog.title'
  | 'rel.dialog.to'
  | 'rel.dialog.type'
  | 'rel.parent'
  | 'rel.removed.toast'
  | 'rel.spouse'
  | 'remove'
  | 'retry'
  | 'save'
  | 'saving'
  | 'search'
  | 'search.back'
  | 'search.noDates'
  | 'search.noResults'
  | 'search.placeholder'
  | 'search.searching'
  | 'search.title'
  | 'settings.appearance.auto'
  | 'settings.appearance.dark'
  | 'settings.appearance.hint'
  | 'settings.appearance.light'
  | 'settings.appearance.title'
  | 'settings.danger.title'
  | 'settings.delete.btn'
  | 'settings.delete.confirm'
  | 'settings.delete.deleting'
  | 'settings.delete.hint'
  | 'settings.delete.submit'
  | 'settings.delete.title'
  | 'settings.deleteData.btn'
  | 'settings.deleteData.confirm'
  | 'settings.deleteData.deleting'
  | 'settings.deleteData.done'
  | 'settings.deleteData.hint'
  | 'settings.deleteData.submit'
  | 'settings.deleteData.title'
  | 'settings.export.btn'
  | 'settings.export.busy'
  | 'settings.export.done'
  | 'settings.export.hint'
  | 'settings.export.title'
  | 'settings.lang.hint'
  | 'settings.lang.saved'
  | 'settings.lang.title'
  | 'settings.loading'
  | 'settings.password.current'
  | 'settings.password.new'
  | 'settings.password.ok'
  | 'settings.password.save'
  | 'settings.password.saving'
  | 'settings.password.title'
  | 'settings.profile.displayName'
  | 'settings.profile.email'
  | 'settings.profile.member'
  | 'settings.profile.title'
  | 'settings.profile.username'
  | 'settings.title'
  | 'sex.female'
  | 'sex.label'
  | 'sex.male'
  | 'tl.add'
  | 'tl.addEvent'
  | 'tl.auto'
  | 'tl.cancel'
  | 'tl.day'
  | 'tl.deleteConfirm'
  | 'tl.desc'
  | 'tl.endDay'
  | 'tl.endMonth'
  | 'tl.endYear'
  | 'tl.era'
  | 'tl.eventTitle'
  | 'tl.marriage.hint'
  | 'tl.marriage.spouse'
  | 'tl.marriage.spousePlaceholder'
  | 'tl.month'
  | 'tl.noEvents'
  | 'tl.place'
  | 'tl.save'
  | 'tl.title'
  | 'tl.type'
  | 'tl.unknownDate'
  | 'tl.until'
  | 'tl.year'
  | 'tree.addPerson'
  | 'tree.addRel'
  | 'tree.back'
  | 'tree.clearSelection'
  | 'tree.emptyTitle'
  | 'tree.export'
  | 'tree.filter'
  | 'tree.fit'
  | 'tree.graphLabel'
  | 'tree.import'
  | 'tree.layoutAuto'
  | 'tree.layoutToggle'
  | 'tree.layoutTree'
  | 'tree.noResults'
  | 'tree.openProfile'
  | 'tree.peopleList'
  | 'tree.relAdd'
  | 'tree.relErr'
  | 'tree.relFrom'
  | 'tree.relFromPlaceholder'
  | 'tree.relTo'
  | 'tree.relToPlaceholder'
  | 'tree.relType'
  | 'tree.resetLayout'
  | 'tree.search'
  | 'tree.zoomIn'
  | 'tree.zoomOut'
  | 'trees.cancel'
  | 'trees.created'
  | 'trees.created.toast'
  | 'trees.delete'
  | 'trees.delete.confirm'
  | 'trees.deleted.toast'
  | 'trees.edit'
  | 'trees.editCancel'
  | 'trees.empty'
  | 'trees.emptyHint'
  | 'trees.emptyImport'
  | 'trees.emptyTitle'
  | 'trees.err.create'
  | 'trees.err.delete'
  | 'trees.err.load'
  | 'trees.err.save'
  | 'trees.menu'
  | 'trees.new'
  | 'trees.new.desc'
  | 'trees.new.name'
  | 'trees.new.rename'
  | 'trees.new.submit'
  | 'trees.new.title'
  | 'trees.open'
  | 'trees.optional'
  | 'trees.persons'
  | 'trees.renamed.toast'
  | 'trees.save'
  | 'trees.title';

export const TRANSLATION_KEYS: readonly TranslationKey[] = [
  'add',
  'admin.action.activate',
  'admin.action.deactivate',
  'admin.action.delete',
  'admin.action.makeAdmin',
  'admin.action.password',
  'admin.action.removeAdmin',
  'admin.actions',
  'admin.confirm.delete',
  'admin.confirm.makeAdmin',
  'admin.confirm.removeAdmin',
  'admin.create.btn',
  'admin.create.cancel',
  'admin.create.displayName',
  'admin.create.email',
  'admin.create.isAdmin',
  'admin.create.password',
  'admin.create.submit',
  'admin.create.submitting',
  'admin.create.title',
  'admin.create.username',
  'admin.created.toast',
  'admin.deleted.toast',
  'admin.err.load',
  'admin.loading',
  'admin.me',
  'admin.pw.cancel',
  'admin.pw.placeholder',
  'admin.pw.save',
  'admin.pw.saved',
  'admin.pw.saving',
  'admin.pw.title',
  'admin.reg.hint',
  'admin.reg.off',
  'admin.reg.on',
  'admin.registered',
  'admin.registration',
  'admin.role.admin',
  'admin.role.user',
  'admin.saved.toast',
  'admin.status.active',
  'admin.status.inactive',
  'admin.table.actions',
  'admin.table.email',
  'admin.table.lang',
  'admin.table.registered',
  'admin.table.role',
  'admin.table.status',
  'admin.table.user',
  'admin.title',
  'auth.hidePassword',
  'auth.language',
  'auth.showPassword',
  'back',
  'cancel',
  'date.clear',
  'date.hint',
  'date.invalid',
  'date.pick',
  'date.unknown',
  'delete',
  'edit',
  'err.delete',
  'err.forbidden',
  'err.load',
  'err.save',
  'err.server',
  'event.birth',
  'event.custom',
  'event.death',
  'event.education',
  'event.marriage',
  'event.move',
  'event.occupation',
  'fam.add',
  'fam.addBtn',
  'fam.adoptive',
  'fam.adoptive.hint',
  'fam.adoptiveChildren',
  'fam.adoptiveParents',
  'fam.cancel',
  'fam.child.hint',
  'fam.children',
  'fam.date',
  'fam.day',
  'fam.month',
  'fam.noRels',
  'fam.parent.hint',
  'fam.parents',
  'fam.place',
  'fam.placePlaceholder',
  'fam.placeholder',
  'fam.remove',
  'fam.removeConfirm',
  'fam.search',
  'fam.spouse.hint',
  'fam.spouses',
  'fam.title',
  'fam.type',
  'fam.year',
  'form.email',
  'form.invalid',
  'form.maxlength',
  'form.minlength',
  'form.range',
  'form.required',
  'import.analyzing',
  'import.back',
  'import.commit',
  'import.done',
  'import.doneTitle',
  'import.err',
  'import.guide',
  'import.importing',
  'import.paste',
  'import.persons',
  'import.preview',
  'import.previewTitle',
  'import.rels',
  'import.title',
  'loading',
  'login.demo',
  'login.demoFill',
  'login.demoPass',
  'login.demoUser',
  'login.error',
  'login.noAccount',
  'login.password',
  'login.register',
  'login.submit',
  'login.submitting',
  'login.tagline',
  'login.title',
  'login.username',
  'media.add',
  'media.avatarBadge',
  'media.deleteConfirm',
  'media.empty',
  'media.setAvatar',
  'media.title',
  'media.uploading',
  'nav.lang',
  'nav.logout',
  'nav.settings',
  'nav.skip',
  'nav.theme.auto',
  'nav.theme.dark',
  'nav.theme.light',
  'nav.users',
  'optional',
  'pd.back',
  'pd.birth',
  'pd.causeOfDeath',
  'pd.death',
  'pd.edit',
  'pd.lifespan.b',
  'pd.lifespan.d',
  'pd.maiden',
  'pd.notes',
  'pd.tab.media',
  'pd.tab.timeline',
  'pe.approx',
  'pe.avatar',
  'pe.avatarHint',
  'pe.avatarPending',
  'pe.basics',
  'pe.birth',
  'pe.birthDay',
  'pe.birthMonth',
  'pe.birthPlace',
  'pe.birthYear',
  'pe.causeOfDeath',
  'pe.death',
  'pe.deathPlace',
  'pe.deleteConfirm',
  'pe.edit',
  'pe.firstName',
  'pe.lastName',
  'pe.maidenName',
  'pe.new',
  'pe.notes',
  'pe.optional',
  'pe.required',
  'pe.save',
  'pe.update',
  'register.displayName',
  'register.email',
  'register.error',
  'register.haveAccount',
  'register.login',
  'register.password',
  'register.passwordHint',
  'register.pendingHint',
  'register.pendingTitle',
  'register.submit',
  'register.submitting',
  'register.tagline',
  'register.title',
  'register.username',
  'rel.added.toast',
  'rel.adoptive',
  'rel.child',
  'rel.dialog.date',
  'rel.dialog.from',
  'rel.dialog.person',
  'rel.dialog.place',
  'rel.dialog.roleHint',
  'rel.dialog.submit',
  'rel.dialog.title',
  'rel.dialog.to',
  'rel.dialog.type',
  'rel.parent',
  'rel.removed.toast',
  'rel.spouse',
  'remove',
  'retry',
  'save',
  'saving',
  'search',
  'search.back',
  'search.noDates',
  'search.noResults',
  'search.placeholder',
  'search.searching',
  'search.title',
  'settings.appearance.auto',
  'settings.appearance.dark',
  'settings.appearance.hint',
  'settings.appearance.light',
  'settings.appearance.title',
  'settings.danger.title',
  'settings.delete.btn',
  'settings.delete.confirm',
  'settings.delete.deleting',
  'settings.delete.hint',
  'settings.delete.submit',
  'settings.delete.title',
  'settings.deleteData.btn',
  'settings.deleteData.confirm',
  'settings.deleteData.deleting',
  'settings.deleteData.done',
  'settings.deleteData.hint',
  'settings.deleteData.submit',
  'settings.deleteData.title',
  'settings.export.btn',
  'settings.export.busy',
  'settings.export.done',
  'settings.export.hint',
  'settings.export.title',
  'settings.lang.hint',
  'settings.lang.saved',
  'settings.lang.title',
  'settings.loading',
  'settings.password.current',
  'settings.password.new',
  'settings.password.ok',
  'settings.password.save',
  'settings.password.saving',
  'settings.password.title',
  'settings.profile.displayName',
  'settings.profile.email',
  'settings.profile.member',
  'settings.profile.title',
  'settings.profile.username',
  'settings.title',
  'sex.female',
  'sex.label',
  'sex.male',
  'tl.add',
  'tl.addEvent',
  'tl.auto',
  'tl.cancel',
  'tl.day',
  'tl.deleteConfirm',
  'tl.desc',
  'tl.endDay',
  'tl.endMonth',
  'tl.endYear',
  'tl.era',
  'tl.eventTitle',
  'tl.marriage.hint',
  'tl.marriage.spouse',
  'tl.marriage.spousePlaceholder',
  'tl.month',
  'tl.noEvents',
  'tl.place',
  'tl.save',
  'tl.title',
  'tl.type',
  'tl.unknownDate',
  'tl.until',
  'tl.year',
  'tree.addPerson',
  'tree.addRel',
  'tree.back',
  'tree.clearSelection',
  'tree.emptyTitle',
  'tree.export',
  'tree.filter',
  'tree.fit',
  'tree.graphLabel',
  'tree.import',
  'tree.layoutAuto',
  'tree.layoutToggle',
  'tree.layoutTree',
  'tree.noResults',
  'tree.openProfile',
  'tree.peopleList',
  'tree.relAdd',
  'tree.relErr',
  'tree.relFrom',
  'tree.relFromPlaceholder',
  'tree.relTo',
  'tree.relToPlaceholder',
  'tree.relType',
  'tree.resetLayout',
  'tree.search',
  'tree.zoomIn',
  'tree.zoomOut',
  'trees.cancel',
  'trees.created',
  'trees.created.toast',
  'trees.delete',
  'trees.delete.confirm',
  'trees.deleted.toast',
  'trees.edit',
  'trees.editCancel',
  'trees.empty',
  'trees.emptyHint',
  'trees.emptyImport',
  'trees.emptyTitle',
  'trees.err.create',
  'trees.err.delete',
  'trees.err.load',
  'trees.err.save',
  'trees.menu',
  'trees.new',
  'trees.new.desc',
  'trees.new.name',
  'trees.new.rename',
  'trees.new.submit',
  'trees.new.title',
  'trees.open',
  'trees.optional',
  'trees.persons',
  'trees.renamed.toast',
  'trees.save',
  'trees.title',
];
