// GENERATED by scripts/gen-i18n-keys.mjs from public/assets/i18n/en.json. Do not edit.
export type TranslationKey =
  | 'actions'
  | 'admin.action.activate'
  | 'admin.action.deactivate'
  | 'admin.action.delete'
  | 'admin.action.makeAdmin'
  | 'admin.action.password'
  | 'admin.action.removeAdmin'
  | 'admin.actions'
  | 'admin.confirm.delete'
  | 'admin.confirm.makeAdmin'
  | 'admin.confirm.removeAdmin'
  | 'admin.create.btn'
  | 'admin.create.cancel'
  | 'admin.create.displayName'
  | 'admin.create.email'
  | 'admin.create.isAdmin'
  | 'admin.create.password'
  | 'admin.create.submit'
  | 'admin.create.title'
  | 'admin.create.username'
  | 'admin.created.toast'
  | 'admin.deleted.toast'
  | 'admin.err.load'
  | 'admin.me'
  | 'admin.pw.cancel'
  | 'admin.pw.placeholder'
  | 'admin.pw.save'
  | 'admin.pw.saved'
  | 'admin.pw.title'
  | 'admin.reg.hint'
  | 'admin.reg.off'
  | 'admin.reg.on'
  | 'admin.registered'
  | 'admin.registration'
  | 'admin.role.admin'
  | 'admin.role.user'
  | 'admin.saved.toast'
  | 'admin.status.active'
  | 'admin.status.inactive'
  | 'admin.table.actions'
  | 'admin.table.email'
  | 'admin.table.registered'
  | 'admin.table.role'
  | 'admin.table.status'
  | 'admin.table.user'
  | 'admin.title'
  | 'auth.hidePassword'
  | 'auth.language'
  | 'auth.showPassword'
  | 'cancel'
  | 'close'
  | 'date.hint'
  | 'date.invalid'
  | 'date.unknown'
  | 'delete'
  | 'edit'
  | 'err.delete'
  | 'err.forbidden'
  | 'err.load'
  | 'err.restore'
  | 'err.save'
  | 'err.server'
  | 'event.birth'
  | 'event.custom'
  | 'event.death'
  | 'event.education'
  | 'event.marriage'
  | 'event.move'
  | 'event.occupation'
  | 'fam.add'
  | 'fam.add.child'
  | 'fam.add.parent'
  | 'fam.add.spouse'
  | 'fam.adoptiveChildren'
  | 'fam.adoptiveParents'
  | 'fam.children'
  | 'fam.noRels'
  | 'fam.parents'
  | 'fam.remove'
  | 'fam.removed.undo'
  | 'fam.spouses'
  | 'fam.title'
  | 'form.email'
  | 'form.invalid'
  | 'form.maxlength'
  | 'form.minlength'
  | 'form.range'
  | 'form.required'
  | 'import.back'
  | 'import.commit'
  | 'import.done'
  | 'import.doneTitle'
  | 'import.err'
  | 'import.guide'
  | 'import.importing'
  | 'import.openTree'
  | 'import.paste'
  | 'import.persons'
  | 'import.preview'
  | 'import.rels'
  | 'import.rule.born'
  | 'import.rule.dates'
  | 'import.rule.died'
  | 'import.rule.maiden'
  | 'import.rule.marriage'
  | 'import.rule.place'
  | 'import.step1'
  | 'import.step2'
  | 'import.title'
  | 'import.warnings'
  | 'loading'
  | 'login.demoFill'
  | 'login.error'
  | 'login.noAccount'
  | 'login.password'
  | 'login.register'
  | 'login.submit'
  | 'login.submitting'
  | 'login.tagline'
  | 'login.title'
  | 'login.username'
  | 'media.actions'
  | 'media.add'
  | 'media.avatarBadge'
  | 'media.avatarSet.toast'
  | 'media.deleted.undo'
  | 'media.dropHint'
  | 'media.empty'
  | 'media.failed.toast'
  | 'media.open'
  | 'media.setAvatar'
  | 'media.title'
  | 'media.tooLarge'
  | 'media.uploaded.toast'
  | 'media.uploading'
  | 'nav.account'
  | 'nav.logout'
  | 'nav.search'
  | 'nav.settings'
  | 'nav.shortcuts'
  | 'nav.skip'
  | 'nav.theme.auto'
  | 'nav.theme.dark'
  | 'nav.theme.light'
  | 'nav.users'
  | 'onb.father'
  | 'onb.finish'
  | 'onb.hero'
  | 'onb.importInstead'
  | 'onb.mother'
  | 'onb.next'
  | 'onb.ready'
  | 'onb.skip'
  | 'onb.start'
  | 'onb.step.parents'
  | 'onb.step.tree'
  | 'onb.step.you'
  | 'onb.treeDescription'
  | 'onb.treeName'
  | 'optional'
  | 'palette.action.addPerson'
  | 'palette.action.addRelation'
  | 'palette.action.import'
  | 'palette.action.langDe'
  | 'palette.action.langEn'
  | 'palette.action.logout'
  | 'palette.action.newTree'
  | 'palette.action.settings'
  | 'palette.action.shortcuts'
  | 'palette.action.themeAuto'
  | 'palette.action.themeDark'
  | 'palette.action.themeLight'
  | 'palette.action.trees'
  | 'palette.action.users'
  | 'palette.group.actions'
  | 'palette.group.people'
  | 'palette.group.trees'
  | 'palette.noResults'
  | 'palette.placeholder'
  | 'palette.results'
  | 'pd.birth'
  | 'pd.causeOfDeath'
  | 'pd.death'
  | 'pd.edit'
  | 'pd.maiden'
  | 'pd.notes'
  | 'pd.tab.media'
  | 'pd.tab.timeline'
  | 'pe.approx'
  | 'pe.avatar'
  | 'pe.avatarHint'
  | 'pe.avatarPending'
  | 'pe.basics'
  | 'pe.birth'
  | 'pe.birthPlace'
  | 'pe.causeOfDeath'
  | 'pe.death'
  | 'pe.deathPlace'
  | 'pe.deleteConfirm'
  | 'pe.deleteTitle'
  | 'pe.deleted.toast'
  | 'pe.discard'
  | 'pe.edit'
  | 'pe.firstName'
  | 'pe.lastName'
  | 'pe.life'
  | 'pe.maidenName'
  | 'pe.new'
  | 'pe.notes'
  | 'pe.save'
  | 'pe.saved.toast'
  | 'pe.unsavedMessage'
  | 'pe.unsavedTitle'
  | 'pe.update'
  | 'register.displayName'
  | 'register.email'
  | 'register.error'
  | 'register.haveAccount'
  | 'register.login'
  | 'register.password'
  | 'register.passwordHint'
  | 'register.pendingHint'
  | 'register.pendingTitle'
  | 'register.submit'
  | 'register.submitting'
  | 'register.tagline'
  | 'register.title'
  | 'register.username'
  | 'rel.added.adoptive'
  | 'rel.added.child'
  | 'rel.added.parent'
  | 'rel.added.spouse'
  | 'rel.added.toast'
  | 'rel.adoptive'
  | 'rel.child'
  | 'rel.dialog.date'
  | 'rel.dialog.from'
  | 'rel.dialog.person'
  | 'rel.dialog.place'
  | 'rel.dialog.roleHint'
  | 'rel.dialog.submit'
  | 'rel.dialog.title'
  | 'rel.dialog.to'
  | 'rel.dialog.type'
  | 'rel.mode.existing'
  | 'rel.mode.label'
  | 'rel.mode.new'
  | 'rel.new.birthPlace'
  | 'rel.new.firstName'
  | 'rel.new.lastName'
  | 'rel.new.sex'
  | 'rel.open'
  | 'rel.parent'
  | 'rel.spouse'
  | 'retry'
  | 'save'
  | 'saving'
  | 'search'
  | 'settings.appearance.auto'
  | 'settings.appearance.dark'
  | 'settings.appearance.hint'
  | 'settings.appearance.light'
  | 'settings.appearance.title'
  | 'settings.danger.title'
  | 'settings.delete.btn'
  | 'settings.delete.hint'
  | 'settings.delete.submit'
  | 'settings.delete.title'
  | 'settings.deleteData.btn'
  | 'settings.deleteData.done'
  | 'settings.deleteData.hint'
  | 'settings.deleteData.submit'
  | 'settings.deleteData.title'
  | 'settings.export.btn'
  | 'settings.export.busy'
  | 'settings.export.done'
  | 'settings.export.hint'
  | 'settings.export.title'
  | 'settings.lang.hint'
  | 'settings.lang.saved'
  | 'settings.lang.title'
  | 'settings.password.current'
  | 'settings.password.new'
  | 'settings.password.ok'
  | 'settings.password.save'
  | 'settings.password.saving'
  | 'settings.password.title'
  | 'settings.profile.displayName'
  | 'settings.profile.email'
  | 'settings.profile.member'
  | 'settings.profile.title'
  | 'settings.profile.username'
  | 'settings.title'
  | 'sex.female'
  | 'sex.label'
  | 'sex.male'
  | 'shortcuts.close'
  | 'shortcuts.move'
  | 'shortcuts.open'
  | 'shortcuts.palette'
  | 'shortcuts.save'
  | 'shortcuts.sheet'
  | 'shortcuts.title'
  | 'shortcuts.tree'
  | 'shortcuts.zoom'
  | 'tl.addEvent'
  | 'tl.auto'
  | 'tl.autoHint'
  | 'tl.deleted.undo'
  | 'tl.desc'
  | 'tl.dialog.add'
  | 'tl.dialog.edit'
  | 'tl.dialog.end'
  | 'tl.dialog.start'
  | 'tl.era'
  | 'tl.eventTitle'
  | 'tl.marriage.hint'
  | 'tl.marriage.spouse'
  | 'tl.noEvents'
  | 'tl.place'
  | 'tl.save'
  | 'tl.saved.toast'
  | 'tl.title'
  | 'tl.type'
  | 'tl.unknownDate'
  | 'tl.until'
  | 'tree.addPerson'
  | 'tree.addRel'
  | 'tree.children'
  | 'tree.closePanel'
  | 'tree.ctx.addChild'
  | 'tree.ctx.addParent'
  | 'tree.ctx.addSpouse'
  | 'tree.ctx.focus'
  | 'tree.ctx.remove'
  | 'tree.deleted.undo'
  | 'tree.edit'
  | 'tree.emptyAddSelf'
  | 'tree.emptyTitle'
  | 'tree.export'
  | 'tree.filter'
  | 'tree.fit'
  | 'tree.graphLabel'
  | 'tree.import'
  | 'tree.layoutToggle'
  | 'tree.noResults'
  | 'tree.openProfile'
  | 'tree.parents'
  | 'tree.peopleList'
  | 'tree.relErr'
  | 'tree.resetLayout'
  | 'tree.showPeople'
  | 'tree.sort'
  | 'tree.sort.birth'
  | 'tree.sort.name'
  | 'tree.spouses'
  | 'tree.zoomIn'
  | 'tree.zoomOut'
  | 'trees.created'
  | 'trees.created.toast'
  | 'trees.delete'
  | 'trees.delete.confirm'
  | 'trees.deleted.toast'
  | 'trees.edit'
  | 'trees.emptyHint'
  | 'trees.emptyTitle'
  | 'trees.err.create'
  | 'trees.err.delete'
  | 'trees.err.load'
  | 'trees.err.save'
  | 'trees.menu'
  | 'trees.new'
  | 'trees.new.desc'
  | 'trees.new.name'
  | 'trees.new.rename'
  | 'trees.new.submit'
  | 'trees.new.title'
  | 'trees.open'
  | 'trees.persons'
  | 'trees.renamed.toast'
  | 'trees.save'
  | 'trees.title'
  | 'undo';

export const TRANSLATION_KEYS: readonly TranslationKey[] = [
  'actions',
  'admin.action.activate',
  'admin.action.deactivate',
  'admin.action.delete',
  'admin.action.makeAdmin',
  'admin.action.password',
  'admin.action.removeAdmin',
  'admin.actions',
  'admin.confirm.delete',
  'admin.confirm.makeAdmin',
  'admin.confirm.removeAdmin',
  'admin.create.btn',
  'admin.create.cancel',
  'admin.create.displayName',
  'admin.create.email',
  'admin.create.isAdmin',
  'admin.create.password',
  'admin.create.submit',
  'admin.create.title',
  'admin.create.username',
  'admin.created.toast',
  'admin.deleted.toast',
  'admin.err.load',
  'admin.me',
  'admin.pw.cancel',
  'admin.pw.placeholder',
  'admin.pw.save',
  'admin.pw.saved',
  'admin.pw.title',
  'admin.reg.hint',
  'admin.reg.off',
  'admin.reg.on',
  'admin.registered',
  'admin.registration',
  'admin.role.admin',
  'admin.role.user',
  'admin.saved.toast',
  'admin.status.active',
  'admin.status.inactive',
  'admin.table.actions',
  'admin.table.email',
  'admin.table.registered',
  'admin.table.role',
  'admin.table.status',
  'admin.table.user',
  'admin.title',
  'auth.hidePassword',
  'auth.language',
  'auth.showPassword',
  'cancel',
  'close',
  'date.hint',
  'date.invalid',
  'date.unknown',
  'delete',
  'edit',
  'err.delete',
  'err.forbidden',
  'err.load',
  'err.restore',
  'err.save',
  'err.server',
  'event.birth',
  'event.custom',
  'event.death',
  'event.education',
  'event.marriage',
  'event.move',
  'event.occupation',
  'fam.add',
  'fam.add.child',
  'fam.add.parent',
  'fam.add.spouse',
  'fam.adoptiveChildren',
  'fam.adoptiveParents',
  'fam.children',
  'fam.noRels',
  'fam.parents',
  'fam.remove',
  'fam.removed.undo',
  'fam.spouses',
  'fam.title',
  'form.email',
  'form.invalid',
  'form.maxlength',
  'form.minlength',
  'form.range',
  'form.required',
  'import.back',
  'import.commit',
  'import.done',
  'import.doneTitle',
  'import.err',
  'import.guide',
  'import.importing',
  'import.openTree',
  'import.paste',
  'import.persons',
  'import.preview',
  'import.rels',
  'import.rule.born',
  'import.rule.dates',
  'import.rule.died',
  'import.rule.maiden',
  'import.rule.marriage',
  'import.rule.place',
  'import.step1',
  'import.step2',
  'import.title',
  'import.warnings',
  'loading',
  'login.demoFill',
  'login.error',
  'login.noAccount',
  'login.password',
  'login.register',
  'login.submit',
  'login.submitting',
  'login.tagline',
  'login.title',
  'login.username',
  'media.actions',
  'media.add',
  'media.avatarBadge',
  'media.avatarSet.toast',
  'media.deleted.undo',
  'media.dropHint',
  'media.empty',
  'media.failed.toast',
  'media.open',
  'media.setAvatar',
  'media.title',
  'media.tooLarge',
  'media.uploaded.toast',
  'media.uploading',
  'nav.account',
  'nav.logout',
  'nav.search',
  'nav.settings',
  'nav.shortcuts',
  'nav.skip',
  'nav.theme.auto',
  'nav.theme.dark',
  'nav.theme.light',
  'nav.users',
  'onb.father',
  'onb.finish',
  'onb.hero',
  'onb.importInstead',
  'onb.mother',
  'onb.next',
  'onb.ready',
  'onb.skip',
  'onb.start',
  'onb.step.parents',
  'onb.step.tree',
  'onb.step.you',
  'onb.treeDescription',
  'onb.treeName',
  'optional',
  'palette.action.addPerson',
  'palette.action.addRelation',
  'palette.action.import',
  'palette.action.langDe',
  'palette.action.langEn',
  'palette.action.logout',
  'palette.action.newTree',
  'palette.action.settings',
  'palette.action.shortcuts',
  'palette.action.themeAuto',
  'palette.action.themeDark',
  'palette.action.themeLight',
  'palette.action.trees',
  'palette.action.users',
  'palette.group.actions',
  'palette.group.people',
  'palette.group.trees',
  'palette.noResults',
  'palette.placeholder',
  'palette.results',
  'pd.birth',
  'pd.causeOfDeath',
  'pd.death',
  'pd.edit',
  'pd.maiden',
  'pd.notes',
  'pd.tab.media',
  'pd.tab.timeline',
  'pe.approx',
  'pe.avatar',
  'pe.avatarHint',
  'pe.avatarPending',
  'pe.basics',
  'pe.birth',
  'pe.birthPlace',
  'pe.causeOfDeath',
  'pe.death',
  'pe.deathPlace',
  'pe.deleteConfirm',
  'pe.deleteTitle',
  'pe.deleted.toast',
  'pe.discard',
  'pe.edit',
  'pe.firstName',
  'pe.lastName',
  'pe.life',
  'pe.maidenName',
  'pe.new',
  'pe.notes',
  'pe.save',
  'pe.saved.toast',
  'pe.unsavedMessage',
  'pe.unsavedTitle',
  'pe.update',
  'register.displayName',
  'register.email',
  'register.error',
  'register.haveAccount',
  'register.login',
  'register.password',
  'register.passwordHint',
  'register.pendingHint',
  'register.pendingTitle',
  'register.submit',
  'register.submitting',
  'register.tagline',
  'register.title',
  'register.username',
  'rel.added.adoptive',
  'rel.added.child',
  'rel.added.parent',
  'rel.added.spouse',
  'rel.added.toast',
  'rel.adoptive',
  'rel.child',
  'rel.dialog.date',
  'rel.dialog.from',
  'rel.dialog.person',
  'rel.dialog.place',
  'rel.dialog.roleHint',
  'rel.dialog.submit',
  'rel.dialog.title',
  'rel.dialog.to',
  'rel.dialog.type',
  'rel.mode.existing',
  'rel.mode.label',
  'rel.mode.new',
  'rel.new.birthPlace',
  'rel.new.firstName',
  'rel.new.lastName',
  'rel.new.sex',
  'rel.open',
  'rel.parent',
  'rel.spouse',
  'retry',
  'save',
  'saving',
  'search',
  'settings.appearance.auto',
  'settings.appearance.dark',
  'settings.appearance.hint',
  'settings.appearance.light',
  'settings.appearance.title',
  'settings.danger.title',
  'settings.delete.btn',
  'settings.delete.hint',
  'settings.delete.submit',
  'settings.delete.title',
  'settings.deleteData.btn',
  'settings.deleteData.done',
  'settings.deleteData.hint',
  'settings.deleteData.submit',
  'settings.deleteData.title',
  'settings.export.btn',
  'settings.export.busy',
  'settings.export.done',
  'settings.export.hint',
  'settings.export.title',
  'settings.lang.hint',
  'settings.lang.saved',
  'settings.lang.title',
  'settings.password.current',
  'settings.password.new',
  'settings.password.ok',
  'settings.password.save',
  'settings.password.saving',
  'settings.password.title',
  'settings.profile.displayName',
  'settings.profile.email',
  'settings.profile.member',
  'settings.profile.title',
  'settings.profile.username',
  'settings.title',
  'sex.female',
  'sex.label',
  'sex.male',
  'shortcuts.close',
  'shortcuts.move',
  'shortcuts.open',
  'shortcuts.palette',
  'shortcuts.save',
  'shortcuts.sheet',
  'shortcuts.title',
  'shortcuts.tree',
  'shortcuts.zoom',
  'tl.addEvent',
  'tl.auto',
  'tl.autoHint',
  'tl.deleted.undo',
  'tl.desc',
  'tl.dialog.add',
  'tl.dialog.edit',
  'tl.dialog.end',
  'tl.dialog.start',
  'tl.era',
  'tl.eventTitle',
  'tl.marriage.hint',
  'tl.marriage.spouse',
  'tl.noEvents',
  'tl.place',
  'tl.save',
  'tl.saved.toast',
  'tl.title',
  'tl.type',
  'tl.unknownDate',
  'tl.until',
  'tree.addPerson',
  'tree.addRel',
  'tree.children',
  'tree.closePanel',
  'tree.ctx.addChild',
  'tree.ctx.addParent',
  'tree.ctx.addSpouse',
  'tree.ctx.focus',
  'tree.ctx.remove',
  'tree.deleted.undo',
  'tree.edit',
  'tree.emptyAddSelf',
  'tree.emptyTitle',
  'tree.export',
  'tree.filter',
  'tree.fit',
  'tree.graphLabel',
  'tree.import',
  'tree.layoutToggle',
  'tree.noResults',
  'tree.openProfile',
  'tree.parents',
  'tree.peopleList',
  'tree.relErr',
  'tree.resetLayout',
  'tree.showPeople',
  'tree.sort',
  'tree.sort.birth',
  'tree.sort.name',
  'tree.spouses',
  'tree.zoomIn',
  'tree.zoomOut',
  'trees.created',
  'trees.created.toast',
  'trees.delete',
  'trees.delete.confirm',
  'trees.deleted.toast',
  'trees.edit',
  'trees.emptyHint',
  'trees.emptyTitle',
  'trees.err.create',
  'trees.err.delete',
  'trees.err.load',
  'trees.err.save',
  'trees.menu',
  'trees.new',
  'trees.new.desc',
  'trees.new.name',
  'trees.new.rename',
  'trees.new.submit',
  'trees.new.title',
  'trees.open',
  'trees.persons',
  'trees.renamed.toast',
  'trees.save',
  'trees.title',
  'undo',
];
