import { Component, input, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TimelineEvent, TimelineEventType, TIMELINE_EVENT_TYPES, PartialDate } from '../../core/api/api-client.service';
import { PartialDatePipe } from '../../shared/pipes/partial-date.pipe';

@Component({
  selector: 'qs-timeline-event-card',
  standalone: true,
  imports: [FormsModule, PartialDatePipe],
  template: `
    @if (!editing()) {
      <div class="event-card">
        <div class="event-card__header">
          @if (ev().start) {
            <span class="event-date">{{ ev().start | partialDate }}</span>
          }
          <span class="event-type-badge" [attr.data-type]="ev().type">{{ ev().type }}</span>
          @if (ev().isAutoGenerated) {
            <span class="auto-badge">auto</span>
          }
          <div class="event-actions">
            @if (!ev().isAutoGenerated) {
              <button class="icon-btn" (click)="startEdit()" title="Edit">✏️</button>
            }
            <button class="icon-btn danger" (click)="removed.emit(ev().id)" title="Delete">🗑️</button>
          </div>
        </div>

        <p class="event-title">{{ ev().title }}</p>
        @if (ev().location) { <p class="event-loc">📍 {{ ev().location }}</p> }
        @if (ev().description) { <p class="event-desc">{{ ev().description }}</p> }
        @if (ev().end) { <p class="event-end">Until {{ ev().end | partialDate }}</p> }
      </div>
    } @else {
      <div class="event-form">
        <div class="form-row">
          <label>Type
            <select [(ngModel)]="draft.type" name="type">
              @for (t of eventTypes; track t) { <option [value]="t">{{ t }}</option> }
            </select>
          </label>
          <label>Title <input [(ngModel)]="draft.title" name="title" required></label>
        </div>
        <div class="form-row">
          <label>Year  <input type="number" [(ngModel)]="startYear"  name="sy" placeholder="YYYY"></label>
          <label>Month <input type="number" [(ngModel)]="startMonth" name="sm" min="1" max="12"></label>
          <label>Day   <input type="number" [(ngModel)]="startDay"   name="sd" min="1" max="31"></label>
        </div>
        <div class="form-row">
          <label>End year  <input type="number" [(ngModel)]="endYear"  name="ey" placeholder="YYYY"></label>
          <label>End month <input type="number" [(ngModel)]="endMonth" name="em" min="1" max="12"></label>
          <label>End day   <input type="number" [(ngModel)]="endDay"   name="ed" min="1" max="31"></label>
        </div>
        <label>Location <input [(ngModel)]="draft.location" name="location" placeholder="City, Country"></label>
        <label>Description <textarea [(ngModel)]="draft.description" name="description" rows="2"></textarea></label>
        <div class="form-actions">
          <button class="primary sm" (click)="submitEdit()" [disabled]="!draft.title">Save</button>
          <button class="sm ghost" (click)="editing.set(false)">Cancel</button>
        </div>
      </div>
    }
  `,
  styles: [`:host { display: block; }`]
})
export class TimelineEventCardComponent {
  readonly ev      = input.required<TimelineEvent>();
  readonly saved   = output<Partial<TimelineEvent>>();
  readonly removed = output<string>();

  editing  = signal(false);
  draft: Partial<TimelineEvent> = {};
  startYear?: number; startMonth?: number; startDay?: number;
  endYear?: number;   endMonth?: number;   endDay?: number;
  eventTypes = TIMELINE_EVENT_TYPES;

  startEdit() {
    const e = this.ev();
    this.draft = { type: e.type, title: e.title, location: e.location, description: e.description };
    this.startYear = e.start?.year; this.startMonth = e.start?.month; this.startDay = e.start?.day;
    this.endYear   = e.end?.year;   this.endMonth   = e.end?.month;   this.endDay   = e.end?.day;
    this.editing.set(true);
  }

  submitEdit() {
    const start: PartialDate | undefined = this.startYear
      ? { year: this.startYear, month: this.startMonth, day: this.startDay }
      : undefined;
    const end: PartialDate | undefined = this.endYear
      ? { year: this.endYear, month: this.endMonth, day: this.endDay }
      : undefined;
    this.saved.emit({ ...this.draft, start, end });
    this.editing.set(false);
  }
}
