import { Component, computed, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatDialog } from '@angular/material/dialog';
import { firstValueFrom } from 'rxjs';
import { TimelineApi, TimelineEventDto } from '../../core/api/generated';
import { I18nService } from '../../core/i18n/i18n.service';
import { TranslatePipe } from '../../core/i18n/translate.pipe';
import { ToastService } from '../../core/ui/toast.service';
import { PartialDatePipe } from '../../shared/pipes/partial-date.pipe';
import { PersonStore } from '../persons/person.store';
import { TimelineEventDialogComponent, TimelineEventDialogData } from './timeline-event-dialog.component';

interface DecadeGroup { decade: number | null; events: TimelineEventDto[]; }

/** Descending compare by (year, month, day); a missing value sorts after a present one at that field. */
function compareStart(a: TimelineEventDto, b: TimelineEventDto): number {
  const ay = a.start?.year ?? null;
  const by = b.start?.year ?? null;
  if (ay !== by) return ay === null ? 1 : by === null ? -1 : by - ay;
  const am = a.start?.month ?? null;
  const bm = b.start?.month ?? null;
  if (am !== bm) return am === null ? 1 : bm === null ? -1 : bm - am;
  const ad = a.start?.day ?? null;
  const bd = b.start?.day ?? null;
  if (ad !== bd) return ad === null ? 1 : bd === null ? -1 : bd - ad;
  return 0;
}

@Component({
  selector: 'qs-timeline',
  imports: [MatButtonModule, MatIconModule, MatChipsModule, MatTooltipModule, TranslatePipe, PartialDatePipe],
  template: `
    <div class="qs-section-header">
      <h2>{{ 'tl.title' | translate }}</h2>
      <button matButton="tonal" (click)="openDialog()"><mat-icon>add</mat-icon>{{ 'tl.addEvent' | translate }}</button>
    </div>
    @if (!store.timeline().length) {
      <div class="qs-empty"><mat-icon class="qs-empty__icon" aria-hidden="true">event_note</mat-icon><p class="qs-muted">{{ 'tl.noEvents' | translate }}</p></div>
    } @else {
      <ol class="qs-tl">
        @for (g of decades(); track g.decade) {
          <li class="qs-tl__decade">
            <p class="qs-tl__decade-label">{{ g.decade === null ? ('tl.unknownDate' | translate) : g.decade + ('tl.era' | translate) }}</p>
            <ul class="qs-tl__list">
              @for (e of g.events; track e.id) {
                <li class="qs-tl__item" [attr.data-event-id]="e.id">
                  <span class="qs-tl__dot" [attr.data-type]="e.type" aria-hidden="true"></span>
                  <div class="qs-tl__card">
                    <div class="qs-tl__meta">
                      @if (e.start) { <span class="qs-tl__date">{{ e.start | partialDate }}</span> }
                      <mat-chip-set><mat-chip>{{ i18n.eventLabel(e.type ?? 'Custom') }}</mat-chip>
                        @if (e.isAutoGenerated) { <mat-chip [matTooltip]="'tl.autoHint' | translate" [attr.aria-label]="('tl.auto' | translate) + ': ' + ('tl.autoHint' | translate)">{{ 'tl.auto' | translate }}</mat-chip> }
                      </mat-chip-set>
                      <span class="qs-tl__spacer"></span>
                      @if (!e.isAutoGenerated) {
                        <button matIconButton data-action="edit" (click)="openDialog(e)" [attr.aria-label]="'edit' | translate"><mat-icon>edit</mat-icon></button>
                        <button matIconButton data-action="delete" (click)="remove(e)" [attr.aria-label]="'delete' | translate"><mat-icon>delete</mat-icon></button>
                      }
                    </div>
                    <p class="qs-tl__title">{{ title(e) }}</p>
                    @if (e.location) { <p class="qs-muted qs-tl__line"><mat-icon aria-hidden="true">place</mat-icon>{{ e.location }}</p> }
                    @if (e.description) { <p class="qs-tl__desc">{{ e.description }}</p> }
                    @if (e.end) { <p class="qs-muted qs-tl__line">{{ 'tl.until' | translate }} {{ e.end | partialDate }}</p> }
                  </div>
                </li>
              }
            </ul>
          </li>
        }
      </ol>
    }
  `,
  styles: [`
    :host { display: block; }
    .qs-tl, .qs-tl__list { list-style: none; margin: 0; padding: 0; }
    .qs-tl { border-left: 2px solid var(--mat-sys-outline-variant); margin-left: 8px; padding-left: 20px; }
    .qs-tl__decade { margin-bottom: 20px; }
    .qs-tl__decade-label { margin: 0 0 8px; font-size: .78rem; letter-spacing: .08em; text-transform: uppercase; color: var(--mat-sys-on-surface-variant); }
    .qs-tl__item { position: relative; margin-bottom: 12px; }
    .qs-tl__dot { position: absolute; left: -27px; top: 18px; width: 12px; height: 12px; border-radius: 50%; background: var(--mat-sys-primary); border: 2px solid var(--mat-sys-surface); }
    .qs-tl__dot[data-type="Marriage"] { background: var(--mat-sys-tertiary); }
    .qs-tl__dot[data-type="Death"] { background: var(--mat-sys-outline); }
    .qs-tl__card { border: 1px solid var(--mat-sys-outline-variant); border-radius: var(--mat-sys-corner-medium); background: var(--mat-sys-surface-container-lowest); padding: 10px 14px; }
    .qs-tl__meta { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
    .qs-tl__date { font-weight: 500; }
    .qs-tl__spacer { flex: 1; }
    .qs-tl__title { margin: 6px 0 2px; font-weight: 500; font-size: 1.05rem; }
    .qs-tl__line { display: flex; align-items: center; gap: 4px; margin: 2px 0; font-size: .9rem; }
    .qs-tl__line mat-icon { font-size: 18px; width: 18px; height: 18px; }
    .qs-tl__desc { margin: 4px 0 0; white-space: pre-wrap; }
  `]
})
export class TimelineComponent {
  readonly store = inject(PersonStore);
  readonly i18n = inject(I18nService);
  private readonly api = inject(TimelineApi);
  private readonly dialog = inject(MatDialog);
  private readonly toast = inject(ToastService);

  readonly decades = computed<DecadeGroup[]>(() => {
    const groups = new Map<number | null, TimelineEventDto[]>();
    for (const e of this.store.timeline()) {
      const y = e.start?.year ?? null;
      const decade = y === null ? null : Math.floor(y / 10) * 10;
      groups.set(decade, [...(groups.get(decade) ?? []), e]);
    }
    return [...groups.entries()]
      .sort(([a], [b]) => (a === null ? 1 : b === null ? -1 : b - a))
      .map(([decade, events]) => ({ decade, events: [...events].sort(compareStart) }));
  });

  title(e: TimelineEventDto): string {
    return e.type === 'Marriage' && e.spouseName ? `${this.i18n.eventLabel('Marriage')} – ${e.spouseName}` : (e.title ?? '');
  }

  async openDialog(event?: TimelineEventDto) {
    const personId = this.store.person()?.id;
    if (!personId) return;
    const data: TimelineEventDialogData = { personId, treePersons: this.store.treePersons(), event };
    const ref = this.dialog.open<TimelineEventDialogComponent, TimelineEventDialogData, TimelineEventDto | undefined>(TimelineEventDialogComponent, { data, width: '560px', maxWidth: '95vw' });
    const saved = await firstValueFrom(ref.afterClosed());
    if (!saved) return;
    this.store.upsertEvent(saved);
    this.toast.success(this.i18n.t('tl.saved.toast'));
  }

  remove(e: TimelineEventDto) {
    const personId = this.store.person()?.id;
    if (!personId || !e.id) return;
    const id = e.id;
    this.api.timelineDelete({ personId, id }).subscribe({
      next: () => {
        this.store.removeEvent(id);
        this.toast.undoable(this.i18n.t('tl.deleted.undo'), () => firstValueFrom(this.api.timelineRestore({ personId, id })).then(() => {
          this.store.reloadTimeline();
          this.toast.success(this.i18n.t('restored.toast'));
        }));
      },
      error: err => this.toast.errorFrom(err, this.i18n.t('err.delete'))
    });
  }
}
