import { Component, input, output, signal, inject, computed } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TimelineEvent, TimelineEventType, TIMELINE_EVENT_TYPES, PartialDate } from '../../core/api/api-client.service';
import { PartialDatePipe } from '../../shared/pipes/partial-date.pipe';
import { PartialDateInputComponent, PartialDateValue } from '../../shared/ui/partial-date-input.component';
import { I18nService } from '../../core/i18n/i18n.service';
import { TranslatePipe } from '../../core/i18n/translate.pipe';

@Component({
  selector: 'qs-timeline-event-card',
  standalone: true,
  imports: [FormsModule, PartialDatePipe, TranslatePipe, PartialDateInputComponent],
  template: `
    @if (!editing()) {
      <div class="event-card">
        <div class="event-card__header">
          @if (ev().start) {
            <span class="event-date">{{ ev().start | partialDate }}</span>
          }
          <span class="event-type-badge" [attr.data-type]="ev().type">{{ i18n.eventLabel(ev().type) }}</span>
          @if (ev().isAutoGenerated) {
            <span class="auto-badge" title="Auto">{{ 'tl.auto' | translate }}</span>
          }
          <div class="event-actions">
            <button class="icon-btn" (click)="startEdit()" [title]="'edit' | translate">✏️</button>
            <button class="icon-btn danger" (click)="removed.emit(ev().id)" [title]="'delete' | translate">🗑️</button>
          </div>
        </div>

        <p class="event-title" [class.event-title--spouse]="ev().type === 'Marriage' && !!resolvedSpouse()">
          {{ displayTitle() }}
        </p>
        @if (ev().location) { <p class="event-loc">📍 {{ ev().location }}</p> }
        @if (ev().description) { <p class="event-desc">{{ ev().description }}</p> }
        @if (ev().end) { <p class="event-end">{{ 'tl.until' | translate }} {{ ev().end | partialDate }}</p> }
      </div>
    } @else {
      <div class="event-form">
        <div class="form-row">
          <label class="field-lbl">
            {{ 'tl.type' | translate }}
            <select [(ngModel)]="draft.type" name="type">
              @for (t of eventTypes; track t) {
                <option [value]="t">{{ i18n.eventLabel(t) }}</option>
              }
            </select>
          </label>
          <label class="field-lbl">
            {{ 'tl.eventTitle' | translate }}
            <input [(ngModel)]="draft.title" name="title" required>
          </label>
        </div>

        <p class="field-lbl" style="margin-bottom:.25rem;font-size:.78rem;font-weight:600;color:var(--c-text-2)">
          {{ 'tl.year' | translate }} / {{ 'tl.month' | translate }} / {{ 'tl.day' | translate }}
        </p>
        <qs-partial-date-input [value]="startDate" (valueChange)="startDate = $event ?? {}" />

        <p class="field-lbl" style="margin:.6rem 0 .25rem;font-size:.78rem;font-weight:600;color:var(--c-text-2)">
          {{ 'tl.endYear' | translate }}
        </p>
        <qs-partial-date-input [value]="endDate" (valueChange)="endDate = $event ?? {}" />

        <label class="field-lbl" style="margin-top:.5rem">
          {{ 'tl.place' | translate }} <input [(ngModel)]="draft.location" name="location">
        </label>
        <label class="field-lbl">
          {{ 'tl.desc' | translate }}
          <textarea [(ngModel)]="draft.description" name="description" rows="2"></textarea>
        </label>
        <div class="form-actions">
          <button class="btn primary sm" (click)="submitEdit()" [disabled]="!draft.title">{{ 'tl.save' | translate }}</button>
          <button class="btn sm ghost" (click)="editing.set(false)">{{ 'cancel' | translate }}</button>
        </div>
      </div>
    }
  `,
  styles: [`
    :host { display: block; }
    .event-title--spouse { font-weight: 600; }
  `]
})
export class TimelineEventCardComponent {
  readonly ev      = input.required<TimelineEvent>();
  readonly saved   = output<Partial<TimelineEvent>>();
  readonly removed = output<string>();

  readonly i18n = inject(I18nService);
  editing    = signal(false);
  draft: Partial<TimelineEvent> = {};
  startDate: PartialDateValue = {};
  endDate:   PartialDateValue = {};
  eventTypes = TIMELINE_EVENT_TYPES;

  resolvedSpouse = computed(() => {
    const ev = this.ev();
    if (ev.type !== 'Marriage') return null;
    if (ev.spouseName) return ev.spouseName;
    return this._spouseFromTitle(ev.title);
  });

  displayTitle = computed(() => {
    const ev = this.ev();
    const spouse = this.resolvedSpouse();
    return ev.type === 'Marriage' && spouse ? `💍 ${spouse}` : ev.title;
  });

  private _spouseFromTitle(title: string): string | null {
    const m = title.match(/(?:\s+mit\s+|\s+with\s+|\s*[–—-]\s*)(.+)$/i);
    return m ? m[1].trim() : null;
  }

  startEdit() {
    const e = this.ev();
    this.draft     = { type: e.type, title: e.title, location: e.location, description: e.description };
    this.startDate = { year: e.start?.year, month: e.start?.month, day: e.start?.day, approx: e.start?.approx };
    this.endDate   = { year: e.end?.year,   month: e.end?.month,   day: e.end?.day,   approx: e.end?.approx };
    this.editing.set(true);
  }

  submitEdit() {
    const start: PartialDate | undefined = this.startDate.year
      ? { year: this.startDate.year, month: this.startDate.month ?? undefined, day: this.startDate.day ?? undefined }
      : undefined;
    const end: PartialDate | undefined = this.endDate.year
      ? { year: this.endDate.year, month: this.endDate.month ?? undefined, day: this.endDate.day ?? undefined }
      : undefined;
    this.saved.emit({ ...this.draft, start, end });
    this.editing.set(false);
  }

  spouseFromTitle(title: string): string | null {
    const m = title.match(/(?:\s+mit\s+|\s+with\s+|\s*[–—-]\s*)(.+)$/i);
    return m ? m[1].trim() : null;
  }
}
