import { TestBed } from '@angular/core/testing';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { MatDialog } from '@angular/material/dialog';
import { signal } from '@angular/core';
import { of } from 'rxjs';
import { describe, expect, it, vi } from 'vitest';
import { TimelineComponent } from './timeline.component';
import { PersonStore } from '../persons/person.store';
import { TimelineApi, TimelineEventDto } from '../../core/api/generated';
import { ConfirmDialogService } from '../../core/ui/confirm-dialog.service';
import { ToastService } from '../../core/ui/toast.service';
import { I18nService } from '../../core/i18n/i18n.service';

const events: TimelineEventDto[] = [
  { id: 'e1', type: 'Marriage', title: 'Marriage', start: { year: 1872 }, isAutoGenerated: true, spouseName: 'Maria Smith' },
  { id: 'e2', type: 'Occupation', title: 'Weaver', start: { year: 1868, month: 3 }, location: 'Bregenz', isAutoGenerated: false },
  { id: 'e3', type: 'Custom', title: 'Undated', isAutoGenerated: false }
];

function setup(confirmResult = true, dialogResult: unknown = undefined) {
  const store = { person: signal({ id: 'p1', treeId: 't1', firstName: 'K', lastName: 'S' }), timeline: signal(events), treePersons: signal([]), upsertEvent: vi.fn(), removeEvent: vi.fn() };
  const api = { timelineDelete: vi.fn(() => of(undefined)) };
  const confirm = { confirm: vi.fn(async () => confirmResult) };
  const toast = { success: vi.fn(), errorFrom: vi.fn(), error: vi.fn(), info: vi.fn() };
  const dialog = { open: vi.fn(() => ({ afterClosed: () => of(dialogResult) })) };
  TestBed.configureTestingModule({ providers: [provideNoopAnimations(),
    { provide: PersonStore, useValue: store }, { provide: TimelineApi, useValue: api }, { provide: ConfirmDialogService, useValue: confirm },
    { provide: ToastService, useValue: toast }, { provide: MatDialog, useValue: dialog },
    { provide: I18nService, useValue: { t: (k: string) => k, dynamic: (k: string) => k, eventLabel: (t: string) => t } }] });
  const fixture = TestBed.createComponent(TimelineComponent);
  fixture.detectChanges();
  return { fixture, cmp: fixture.componentInstance, store, api, confirm, dialog, toast };
}

describe('TimelineComponent', () => {
  it('groups by decade, newest first, unknown last, and shows spouse for marriages', () => {
    const { cmp, fixture } = setup();
    expect(cmp.decades().map(d => d.decade)).toEqual([1870, 1860, null]);
    expect((fixture.nativeElement as HTMLElement).textContent).toContain('Maria Smith');
  });

  it('hides edit/delete on auto-generated events', () => {
    const { fixture } = setup();
    const cards = (fixture.nativeElement as HTMLElement).querySelectorAll('[data-event-id]');
    expect(cards[0].getAttribute('data-event-id')).toBe('e1');
    expect(cards[0].querySelector('button[data-action=delete]')).toBeNull();
    expect(cards[1].querySelector('button[data-action=delete]')).not.toBeNull();
  });

  it('deletes after confirm and updates the store', async () => {
    const { cmp, api, store } = setup(true);
    await cmp.remove(events[1]);
    expect(api.timelineDelete).toHaveBeenCalledWith({ personId: 'p1', id: 'e2' });
    expect(store.removeEvent).toHaveBeenCalledWith('e2');
  });

  it('upserts the dialog result', async () => {
    const { cmp, store, toast } = setup(true, { id: 'e9', type: 'Custom', title: 'New' });
    await cmp.openDialog();
    expect(store.upsertEvent).toHaveBeenCalledWith(expect.objectContaining({ id: 'e9' }));
    expect(toast.success).toHaveBeenCalledWith('tl.saved.toast');
  });
});
