using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Application.Timeline;

public record TimelineEventDto(
    Guid Id, TimelineEventType Type, string Title, string? Description,
    PartialDate? Start, PartialDate? End, string? Location,
    bool IsAutoGenerated, Guid? SourceRelationshipId, string? SpouseName = null);
