using Qseng.Domain.Common;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Domain.Entities;

public class TimelineEvent : Entity
{
    public Guid PersonId { get; set; }
    public TimelineEventType Type { get; set; }
    public string Title { get; set; } = "";
    public string? Description { get; set; }
    public PartialDate? Start { get; set; }
    public PartialDate? End { get; set; }
    public string? Location { get; set; }
    public string? MetadataJson { get; set; }
    public bool IsAutoGenerated { get; set; }
    public Guid? SourceRelationshipId { get; set; }

    public DateTime SortableDate => Start?.SortableDate ?? new DateTime(9999, 12, 31);
}
