using Qseng.Domain.Common;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Domain.Entities;

public class TimelineEvent : Entity, ISoftDeletable
{
    public Guid PersonId { get; set; }
    public TimelineEventType Type { get; set; }
    public string Title { get; set; } = "";
    public string? Description { get; set; }
    public PartialDate? Start { get; set; }
    public PartialDate? End { get; set; }
    public string? Location { get; set; }
    public string? MetadataJson { get; set; }
    public bool IsAutoGenerated { get; set; }
    public Guid? SourceRelationshipId { get; set; }
    public DateTime? DeletedAt { get; set; }
    public Guid? DeletionBatchId { get; set; }

    /// <summary>
    /// Persisted, indexed ordering key derived from <see cref="Start"/> as
    /// yyyyMMdd (missing month/day become 00). Zero means "date unknown", which
    /// sorts last under ORDER BY … DESC. Maintained by the DbContext on save;
    /// never set it by hand.
    /// </summary>
    public int StartSortKey { get; private set; }

    public void RecomputeSortKey() =>
        StartSortKey = Start?.Year is { } year
            ? year * 10000 + (Start.Month ?? 0) * 100 + (Start.Day ?? 0)
            : 0;

    public DateTime SortableDate => Start?.SortableDate ?? new DateTime(9999, 12, 31);
}
