using FluentValidation;
using MediatR;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;
using Qseng.Application.Timeline.AddTimelineEvent;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Application.Timeline.UpdateTimelineEvent;

public record UpdateTimelineEventCommand(
    Guid Id, TimelineEventType Type, string Title, string? Description,
    PartialDate? Start, PartialDate? End, string? Location, string? MetadataJson)
    : IRequest<Result<TimelineEventDto>>;

public class UpdateTimelineEventValidator : AbstractValidator<UpdateTimelineEventCommand>
{
    public UpdateTimelineEventValidator()
    {
        RuleFor(x => x.Title).NotEmpty().MaximumLength(300);
    }
}

public class UpdateTimelineEventHandler : IRequestHandler<UpdateTimelineEventCommand, Result<TimelineEventDto>>
{
    private readonly IQsengDbContext _db;
    public UpdateTimelineEventHandler(IQsengDbContext db) => _db = db;

    public async Task<Result<TimelineEventDto>> Handle(UpdateTimelineEventCommand cmd, CancellationToken ct)
    {
        var ev = await _db.TimelineEvents.FindAsync([cmd.Id], ct);
        if (ev is null) return Result<TimelineEventDto>.NotFound("Event not found.");

        ev.Type = cmd.Type; ev.Title = cmd.Title; ev.Description = cmd.Description;
        ev.Start = cmd.Start; ev.End = cmd.End; ev.Location = cmd.Location;
        ev.MetadataJson = cmd.MetadataJson;
        ev.IsAutoGenerated = false;

        await _db.SaveChangesAsync(ct);
        return Result<TimelineEventDto>.Ok(AddTimelineEventHandler.ToDto(ev));
    }
}
