using MediatR;
using Microsoft.EntityFrameworkCore;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;

namespace Qseng.Application.Timeline.GetPersonTimeline;

public record GetPersonTimelineQuery(Guid PersonId) : IRequest<Result<IReadOnlyList<TimelineEventDto>>>;

public class GetPersonTimelineHandler : IRequestHandler<GetPersonTimelineQuery, Result<IReadOnlyList<TimelineEventDto>>>
{
    private readonly IQsengDbContext _db;
    public GetPersonTimelineHandler(IQsengDbContext db) => _db = db;

    public async Task<Result<IReadOnlyList<TimelineEventDto>>> Handle(GetPersonTimelineQuery q, CancellationToken ct)
    {
        var events = await _db.TimelineEvents
            .Where(t => t.PersonId == q.PersonId)
            .OrderBy(t => t.Start != null ? t.Start.Year ?? 9999 : 9999)
            .ThenBy(t => t.Start != null ? t.Start.Month ?? 1 : 1)
            .ThenBy(t => t.Start != null ? t.Start.Day ?? 1 : 1)
            .Select(t => new TimelineEventDto(
                t.Id, t.Type, t.Title, t.Description,
                t.Start, t.End, t.Location,
                t.IsAutoGenerated, t.SourceRelationshipId))
            .ToListAsync(ct);

        return Result<IReadOnlyList<TimelineEventDto>>.Ok(events);
    }
}
