using MediatR;
using Microsoft.EntityFrameworkCore;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;
using Qseng.Domain.Enums;

namespace Qseng.Application.Timeline.GetPersonTimeline;

public record GetPersonTimelineQuery(Guid PersonId) : IRequest<Result<IReadOnlyList<TimelineEventDto>>>;

public class GetPersonTimelineHandler : IRequestHandler<GetPersonTimelineQuery, Result<IReadOnlyList<TimelineEventDto>>>
{
    private readonly IQsengDbContext _db;
    private readonly ICurrentUser _currentUser;

    public GetPersonTimelineHandler(IQsengDbContext db, ICurrentUser currentUser)
    {
        _db = db;
        _currentUser = currentUser;
    }

    public async Task<Result<IReadOnlyList<TimelineEventDto>>> Handle(GetPersonTimelineQuery q, CancellationToken ct)
    {
        var person = await _db.Persons.FirstOrDefaultAsync(p => p.Id == q.PersonId, ct);
        if (person is null) return Result<IReadOnlyList<TimelineEventDto>>.NotFound("Person not found.");

        var tree = await _db.Trees.FindAsync([person.TreeId], ct);
        if (tree is null) return Result<IReadOnlyList<TimelineEventDto>>.NotFound("Person not found.");
        if (tree.OwnerId != _currentUser.UserId) return Result<IReadOnlyList<TimelineEventDto>>.Fail("Forbidden.", 403);

        // StartSortKey is an indexed yyyyMMdd integer; unknown dates are 0 and
        // therefore sort last. Ordering happens in the database.
        var events = await _db.TimelineEvents
            .AsNoTracking()
            .Where(t => t.PersonId == q.PersonId)
            .OrderByDescending(t => t.StartSortKey)
            .Select(t => new TimelineEventDto(
                t.Id, t.Type, t.Title, t.Description,
                t.Start, t.End, t.Location,
                t.IsAutoGenerated, t.SourceRelationshipId))
            .ToListAsync(ct);

        // Enrich marriage events with the spouse's name from the source relationship.
        var relIds = events
            .Where(e => e.Type == TimelineEventType.Marriage && e.SourceRelationshipId.HasValue)
            .Select(e => e.SourceRelationshipId!.Value)
            .Distinct()
            .ToList();

        if (relIds.Count > 0)
        {
            var rels = await _db.Relationships
                .AsNoTracking()
                .Where(r => relIds.Contains(r.Id))
                .ToListAsync(ct);

            var otherPersonIds = rels
                .Select(r => r.FromPersonId == q.PersonId ? r.ToPersonId : r.FromPersonId)
                .Distinct()
                .ToList();

            var spouseMap = (await _db.Persons
                .AsNoTracking()
                .Where(p => otherPersonIds.Contains(p.Id))
                .Select(p => new { p.Id, p.FirstName, p.LastName })
                .ToListAsync(ct))
                .ToDictionary(p => p.Id, p => $"{p.FirstName} {p.LastName}");

            var relMap = rels.ToDictionary(
                r => r.Id,
                r => spouseMap.GetValueOrDefault(r.FromPersonId == q.PersonId ? r.ToPersonId : r.FromPersonId));

            events = events.Select(e =>
                e.SourceRelationshipId.HasValue && relMap.TryGetValue(e.SourceRelationshipId.Value, out var name) && name is not null
                    ? e with { SpouseName = name }
                    : e).ToList();
        }

        return Result<IReadOnlyList<TimelineEventDto>>.Ok(events);
    }
}
