using Qseng.Domain.Entities;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;
using Qseng.Infrastructure.Persistence;

namespace Qseng.Infrastructure.Seeding;

internal static class DemoData
{
    public static void Build(Guid treeId, QsengDbContext db)
    {
        var johannEgger  = MkPerson(treeId, "Johann",  "Egger",    birth: new(1878, 4, 12),  death: new(1949, 11, 3),  birthPlace: "Tirol");
        var maria        = MkPerson(treeId, "Maria",   "Sulzer",   maiden: "Sulzer",           birth: new(1882, 6, 1),   death: new(1955, 2, 14));
        var franzEgger   = MkPerson(treeId, "Franz",   "Egger",    birth: new(1908, 9, 22),  death: new(1981, 5, 9));
        var anna         = MkPerson(treeId, "Anna",    "Spath",    maiden: "Spath",            birth: new(1912, 1, 30),  death: new(1990, 7, 18));
        var peterEgger   = MkPerson(treeId, "Peter",   "Egger",    birth: new(1940, 3, 4),   death: new(2018, 10, 22));
        var heleneSulzer = MkPerson(treeId, "Helene",  "Sulzer",   maiden: "Sulzer",           birth: new(1944, 8, 15));
        var thomas       = MkPerson(treeId, "Thomas",  "Egger",    birth: new(1972, 5, 11));
        var laura        = MkPerson(treeId, "Laura",   "Spath",    maiden: "Spath",            birth: new(1975, 12, 2));
        var sophie       = MkPerson(treeId, "Sophie",  "Egger",    birth: new(2003, 6, 19));
        var lukas        = MkPerson(treeId, "Lukas",   "Egger",    birth: new(2006, 1, 7));

        db.Persons.AddRange(johannEgger, maria, franzEgger, anna, peterEgger, heleneSulzer, thomas, laura, sophie, lukas);

        MkSpouse(treeId, db, johannEgger, maria,        1905);
        MkSpouse(treeId, db, franzEgger,  anna,         1935);
        MkSpouse(treeId, db, peterEgger,  heleneSulzer, 1968);
        MkSpouse(treeId, db, thomas,      laura,        2000);

        MkParent(treeId, db, johannEgger, franzEgger);
        MkParent(treeId, db, maria,       franzEgger);
        MkParent(treeId, db, franzEgger,  peterEgger);
        MkParent(treeId, db, anna,        peterEgger);
        MkParent(treeId, db, peterEgger,  thomas);
        MkParent(treeId, db, heleneSulzer, thomas);
        MkParent(treeId, db, thomas,      sophie);
        MkParent(treeId, db, laura,       sophie);
        MkParent(treeId, db, thomas,      lukas);
        MkParent(treeId, db, laura,       lukas);

        db.TimelineEvents.Add(new TimelineEvent
        {
            PersonId = peterEgger.Id, Type = TimelineEventType.Occupation,
            Title = "Tischlermeister", Start = new PartialDate(1965, null, null), Location = "Innsbruck"
        });
        db.TimelineEvents.Add(new TimelineEvent
        {
            PersonId = thomas.Id, Type = TimelineEventType.Move,
            Title = "Umzug nach Wien", Start = new PartialDate(1995, 9, null), Location = "Wien"
        });

        // Marriage timeline events for all spouses
        AddMarriageEvents(treeId, db, johannEgger, maria,        1905);
        AddMarriageEvents(treeId, db, franzEgger,  anna,         1935);
        AddMarriageEvents(treeId, db, peterEgger,  heleneSulzer, 1968);
        AddMarriageEvents(treeId, db, thomas,      laura,        2000);
    }

    private static void AddMarriageEvents(Guid treeId, QsengDbContext db, Person a, Person b, int year)
    {
        var rel = db.Relationships.Local.FirstOrDefault(r =>
            r.FromPersonId == a.Id && r.ToPersonId == b.Id && r.Type == RelationshipType.Spouse);
        if (rel is null) return;

        foreach (var personId in new[] { a.Id, b.Id })
        {
            db.TimelineEvents.Add(new TimelineEvent
            {
                PersonId = personId, Type = TimelineEventType.Marriage, Title = "Marriage",
                Start = new PartialDate(year, null, null), IsAutoGenerated = true,
                SourceRelationshipId = rel.Id
            });
        }
    }

    private static Person MkPerson(Guid treeId, string first, string last,
        PartialDate? birth = null, PartialDate? death = null,
        string? maiden = null, string? birthPlace = null)
        => new()
        {
            TreeId = treeId, FirstName = first, LastName = last, MaidenName = maiden,
            Birth = birth, Death = death, BirthPlace = birthPlace
        };

    private static void MkSpouse(Guid treeId, QsengDbContext db, Person a, Person b, int year)
        => db.Relationships.Add(new Relationship
        {
            TreeId = treeId, FromPersonId = a.Id, ToPersonId = b.Id,
            Type = RelationshipType.Spouse, StartYear = year
        });

    private static void MkParent(Guid treeId, QsengDbContext db, Person parent, Person child)
        => db.Relationships.Add(new Relationship
        {
            TreeId = treeId, FromPersonId = parent.Id, ToPersonId = child.Id,
            Type = RelationshipType.Parent
        });
}
