// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qseng.Infrastructure.Persistence;

#nullable disable

namespace Qseng.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QsengDbContext))]
    partial class QsengDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qseng.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("text");

                    b.Property<string>("CauseOfDeath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeathPlace")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.HasIndex("TreeId", "LastName", "FirstName");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndDay")
                        .HasColumnType("integer");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("StartDay")
                        .HasColumnType("integer");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TreeId", "FromPersonId");

                    b.HasIndex("TreeId", "ToPersonId");

                    b.HasIndex("TreeId", "FromPersonId", "ToPersonId", "Type")
                        .IsUnique();

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceRelationshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("timeline_events", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("trees", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("de");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Person", b =>
                {
                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "Birth", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Approx")
                                .HasColumnType("boolean")
                                .HasColumnName("birth_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("birth_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("birth_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("birth_year");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "Death", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Approx")
                                .HasColumnType("boolean")
                                .HasColumnName("death_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("death_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("death_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("death_year");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Birth");

                    b.Navigation("Death");
                });

            modelBuilder.Entity("Qseng.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.Person", null)
                        .WithMany("Timeline")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "End", b1 =>
                        {
                            b1.Property<Guid>("TimelineEventId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Approx")
                                .HasColumnType("boolean")
                                .HasColumnName("end_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("end_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("end_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("end_year");

                            b1.HasKey("TimelineEventId");

                            b1.ToTable("timeline_events");

                            b1.WithOwner()
                                .HasForeignKey("TimelineEventId");
                        });

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "Start", b1 =>
                        {
                            b1.Property<Guid>("TimelineEventId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Approx")
                                .HasColumnType("boolean")
                                .HasColumnName("start_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("start_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("start_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("start_year");

                            b1.HasKey("TimelineEventId");

                            b1.ToTable("timeline_events");

                            b1.WithOwner()
                                .HasForeignKey("TimelineEventId");
                        });

                    b.Navigation("End");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Person", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
