using NSubstitute;
using Qseng.Application.Abstractions;
using Qseng.Domain.Entities;
using Qseng.Domain.Enums;

namespace Qseng.Application.Tests.Trash;

internal static class TrashFixtures
{
    public static ICurrentUser FakeUser(Guid id) { var u = Substitute.For<ICurrentUser>(); u.UserId.Returns(id); return u; }

    public static async Task<(IQsengDbContext db, Guid owner, Person a, Person b, Relationship rel, TimelineEvent ev, Qseng.Domain.Entities.Media media)> SeedFamilyAsync()
    {
        var db = TestDb.Create();
        var owner = Guid.NewGuid();
        var tree = new Tree { OwnerId = owner, Name = "T" };
        db.Trees.Add(tree);
        var a = new Person { TreeId = tree.Id, FirstName = "A", LastName = "X" };
        var b = new Person { TreeId = tree.Id, FirstName = "B", LastName = "X" };
        db.Persons.AddRange(a, b);
        var rel = new Relationship { TreeId = tree.Id, FromPersonId = a.Id, ToPersonId = b.Id, Type = RelationshipType.Spouse };
        db.Relationships.Add(rel);
        var ev = new TimelineEvent { PersonId = a.Id, Type = TimelineEventType.Marriage, Title = "Wedding", IsAutoGenerated = true, SourceRelationshipId = rel.Id };
        db.TimelineEvents.Add(ev);
        var media = new Qseng.Domain.Entities.Media { PersonId = a.Id, Url = "/u/a.jpg", Kind = MediaKind.Photo, IsAvatar = true };
        db.Media.Add(media);
        await db.SaveChangesAsync();
        return (db, owner, a, b, rel, ev, media);
    }
}
