using FluentValidation;
using MediatR;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;
using Qseng.Domain.Entities;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Application.Timeline.AddTimelineEvent;

public record AddTimelineEventCommand(
    Guid PersonId, TimelineEventType Type, string Title, string? Description,
    PartialDate? Start, PartialDate? End, string? Location, string? MetadataJson)
    : IRequest<Result<TimelineEventDto>>;

public class AddTimelineEventValidator : AbstractValidator<AddTimelineEventCommand>
{
    public AddTimelineEventValidator()
    {
        RuleFor(x => x.PersonId).NotEmpty();
        RuleFor(x => x.Title).NotEmpty().MaximumLength(300);
    }
}

public class AddTimelineEventHandler : IRequestHandler<AddTimelineEventCommand, Result<TimelineEventDto>>
{
    private readonly IQsengDbContext _db;
    public AddTimelineEventHandler(IQsengDbContext db) => _db = db;

    public async Task<Result<TimelineEventDto>> Handle(AddTimelineEventCommand cmd, CancellationToken ct)
    {
        var person = await _db.Persons.FindAsync([cmd.PersonId], ct);
        if (person is null) return Result<TimelineEventDto>.NotFound("Person not found.");

        var ev = new TimelineEvent
        {
            PersonId = cmd.PersonId, Type = cmd.Type, Title = cmd.Title,
            Description = cmd.Description, Start = cmd.Start, End = cmd.End,
            Location = cmd.Location, MetadataJson = cmd.MetadataJson
        };
        _db.TimelineEvents.Add(ev);
        await _db.SaveChangesAsync(ct);
        return Result<TimelineEventDto>.Ok(ToDto(ev));
    }

    internal static TimelineEventDto ToDto(TimelineEvent e) => new(
        e.Id, e.Type, e.Title, e.Description, e.Start, e.End, e.Location,
        e.IsAutoGenerated, e.SourceRelationshipId);
}
