import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { AuthResponse } from '../auth/auth.service';

export interface PartialDate { year?: number; month?: number; day?: number; approx?: boolean; }

export interface Tree { id: string; name: string; description?: string; createdAt: string; personCount: number; }

export interface Person {
  id: string; treeId: string;
  firstName: string; lastName: string; maidenName?: string;
  sex: Sex; notes?: string;
  birth?: PartialDate; death?: PartialDate;
  birthPlace?: string; deathPlace?: string;
  causeOfDeath?: string;
  avatarUrl?: string;
}

export interface Relationship {
  id: string; treeId: string;
  fromPersonId: string; toPersonId: string;
  type: RelationshipType;
  startYear?: number; startMonth?: number; startDay?: number;
  endYear?: number; endMonth?: number; endDay?: number;
  notes?: string;
}

export interface PersonRelation {
  relationshipId: string;
  type: RelationshipType;
  direction: 'from' | 'to';
  relatedPersonId: string;
  relatedFirstName: string;
  relatedLastName: string;
  relatedMaidenName?: string;
  startYear?: number; startMonth?: number; startDay?: number;
  endYear?: number; endMonth?: number; endDay?: number;
  notes?: string;
}

export interface TimelineEvent {
  id: string;
  type: TimelineEventType;
  title: string;
  description?: string;
  start?: PartialDate;
  end?: PartialDate;
  location?: string;
  isAutoGenerated: boolean;
  sourceRelationshipId?: string;
  spouseName?: string;
}

export interface ImportReport {
  personsCreated: number;
  relationshipsCreated: number;
  warnings: string[];
  isDryRun: boolean;
}

export interface UserProfile {
  id: string;
  username: string;
  email?: string;
  displayName: string;
  isAdmin: boolean;
  language: string;
  createdAt: string;
}

export interface UserSummary {
  id: string;
  username: string;
  email?: string;
  displayName: string;
  isAdmin: boolean;
  isActive: boolean;
  language: string;
  createdAt: string;
}

export interface SiteSettings {
  registrationEnabled: boolean;
}

export interface MediaItem {
  id: string;
  personId: string;
  url: string;
  caption?: string;
  kind: 'Photo' | 'Document' | 'Audio';
  createdAt: string;
  isAvatar: boolean;
}

export type Sex = 'Male' | 'Female';
export type RelationshipType = 'Parent' | 'Spouse' | 'Adoptive';
export type TimelineEventType = 'Birth' | 'Death' | 'Marriage' | 'Move' | 'Occupation' | 'Education' | 'Custom';

export const SEX_OPTIONS: Sex[] = ['Male', 'Female'];
export const RELATIONSHIP_TYPES: RelationshipType[] = ['Parent', 'Spouse', 'Adoptive'];
export const TIMELINE_EVENT_TYPES: TimelineEventType[] = ['Birth', 'Death', 'Marriage', 'Move', 'Occupation', 'Education', 'Custom'];

@Injectable({ providedIn: 'root' })
export class ApiClient {
  private base = environment.apiBase;
  constructor(private http: HttpClient) {}

  // Trees
  getTrees() { return this.http.get<Tree[]>(`${this.base}/trees`); }
  createTree(name: string, description?: string) { return this.http.post<Tree>(`${this.base}/trees`, { name, description }); }
  updateTree(id: string, name: string, description?: string) { return this.http.put<Tree>(`${this.base}/trees/${id}`, { name, description }); }
  deleteTree(id: string) { return this.http.delete<void>(`${this.base}/trees/${id}`); }

  // Persons
  getPersonsByTree(treeId: string, search?: string) {
    let params = new HttpParams();
    if (search) params = params.set('search', search);
    return this.http.get<Person[]>(`${this.base}/trees/${treeId}/persons`, { params });
  }
  getPerson(id: string) { return this.http.get<Person>(`${this.base}/persons/${id}`); }
  getPersonRelations(id: string) { return this.http.get<PersonRelation[]>(`${this.base}/persons/${id}/relations`); }
  createPerson(treeId: string, body: Partial<Person>) { return this.http.post<Person>(`${this.base}/trees/${treeId}/persons`, body); }
  updatePerson(id: string, body: Partial<Person>) { return this.http.put<Person>(`${this.base}/persons/${id}`, body); }
  deletePerson(id: string) { return this.http.delete<void>(`${this.base}/persons/${id}`); }

  // Relationships
  getRelationships(treeId: string) { return this.http.get<Relationship[]>(`${this.base}/trees/${treeId}/relationships`); }
  createRelationship(treeId: string, body: Partial<Relationship>) { return this.http.post<Relationship>(`${this.base}/trees/${treeId}/relationships`, body); }
  deleteRelationship(treeId: string, id: string) { return this.http.delete<void>(`${this.base}/trees/${treeId}/relationships/${id}`); }

  // Timeline
  getTimeline(personId: string) { return this.http.get<TimelineEvent[]>(`${this.base}/persons/${personId}/timeline`); }
  addTimelineEvent(personId: string, body: Partial<TimelineEvent>) { return this.http.post<TimelineEvent>(`${this.base}/persons/${personId}/timeline`, body); }
  updateTimelineEvent(personId: string, id: string, body: Partial<TimelineEvent>) { return this.http.put<TimelineEvent>(`${this.base}/persons/${personId}/timeline/${id}`, body); }
  deleteTimelineEvent(personId: string, id: string) { return this.http.delete<void>(`${this.base}/persons/${personId}/timeline/${id}`); }

  // Import
  previewImport(treeId: string, text: string) { return this.http.post<ImportReport>(`${this.base}/trees/${treeId}/import/preview`, { text }); }
  commitImport(treeId: string, text: string) { return this.http.post<ImportReport>(`${this.base}/trees/${treeId}/import/commit`, { text }); }

  // User profile & settings
  getProfile() { return this.http.get<UserProfile>(`${this.base}/user/profile`); }
  /** Returns a fresh session: other devices are signed out, this one is not. */
  changePassword(currentPassword: string, newPassword: string) {
    return this.http.patch<AuthResponse>(`${this.base}/user/password`, { currentPassword, newPassword });
  }
  changeLanguage(language: string) {
    return this.http.patch<void>(`${this.base}/user/language`, { language });
  }
  exportData() { return this.http.get(`${this.base}/user/export`, { responseType: 'blob' }); }
  deleteOwnData(password: string) {
    return this.http.delete<void>(`${this.base}/user/data`, { body: { password } });
  }
  deleteOwnAccount(password: string) {
    return this.http.delete<void>(`${this.base}/user/account`, { body: { password } });
  }

  // Admin – users
  listUsers() { return this.http.get<UserSummary[]>(`${this.base}/admin/users`); }
  adminCreateUser(body: { username: string; password: string; displayName?: string; email?: string; isAdmin: boolean }) {
    return this.http.post<UserSummary>(`${this.base}/admin/users`, body);
  }
  setUserActive(id: string, active: boolean) {
    return this.http.patch<void>(`${this.base}/admin/users/${id}/active`, { active });
  }
  setUserAdmin(id: string, admin: boolean) {
    return this.http.patch<void>(`${this.base}/admin/users/${id}/admin`, { admin });
  }
  adminChangeUserPassword(id: string, newPassword: string) {
    return this.http.patch<void>(`${this.base}/admin/users/${id}/password`, { newPassword });
  }
  adminDeleteUser(id: string) { return this.http.delete<void>(`${this.base}/admin/users/${id}`); }

  // Admin – settings
  getSiteSettings() { return this.http.get<SiteSettings>(`${this.base}/admin/settings`); }
  setRegistrationEnabled(enabled: boolean) {
    return this.http.patch<void>(`${this.base}/admin/settings/registration`, { enabled });
  }

  // Media
  getPersonMedia(personId: string) { return this.http.get<MediaItem[]>(`${this.base}/persons/${personId}/media`); }
  uploadMedia(personId: string, file: File, caption?: string, kind = 'Photo') {
    const fd = new FormData();
    fd.append('file', file);
    if (caption) fd.append('caption', caption);
    fd.append('kind', kind);
    return this.http.post<MediaItem>(`${this.base}/persons/${personId}/media`, fd);
  }
  setAvatar(personId: string, mediaId: string) {
    return this.http.put<void>(`${this.base}/persons/${personId}/media/${mediaId}/avatar`, {});
  }
  deleteMedia(personId: string, mediaId: string) {
    return this.http.delete<void>(`${this.base}/persons/${personId}/media/${mediaId}`);
  }
}
