import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { environment } from '../../../environments/environment';

export interface PartialDate { year?: number; month?: number; day?: number; approx?: boolean; }

export interface Tree { id: string; name: string; description?: string; createdAt: string; }

export interface Person {
  id: string; treeId: string;
  firstName: string; lastName: string; maidenName?: string;
  sex: Sex; notes?: string;
  birth?: PartialDate; death?: PartialDate;
  birthPlace?: string; deathPlace?: string;
}

export interface Relationship {
  id: string; treeId: string;
  fromPersonId: string; toPersonId: string;
  type: RelationshipType;
  startYear?: number; startMonth?: number; startDay?: number;
  endYear?: number; endMonth?: number; endDay?: number;
  notes?: string;
}

export interface PersonRelation {
  relationshipId: string;
  type: RelationshipType;
  direction: 'from' | 'to';
  relatedPersonId: string;
  relatedFirstName: string;
  relatedLastName: string;
  relatedMaidenName?: string;
  startYear?: number; startMonth?: number; startDay?: number;
  endYear?: number; endMonth?: number; endDay?: number;
}

export interface TimelineEvent {
  id: string;
  type: TimelineEventType;
  title: string;
  description?: string;
  start?: PartialDate;
  end?: PartialDate;
  location?: string;
  isAutoGenerated: boolean;
  sourceRelationshipId?: string;
}

export interface ImportReport {
  personsCreated: number;
  relationshipsCreated: number;
  warnings: string[];
  isDryRun: boolean;
}

export type Sex = 'Unknown' | 'Male' | 'Female' | 'Other';
export type RelationshipType = 'Parent' | 'Spouse' | 'Adoptive';
export type TimelineEventType = 'Birth' | 'Death' | 'Marriage' | 'Move' | 'Occupation' | 'Education' | 'Custom';

export const SEX_OPTIONS: Sex[] = ['Unknown', 'Male', 'Female', 'Other'];
export const RELATIONSHIP_TYPES: RelationshipType[] = ['Parent', 'Spouse', 'Adoptive'];
export const TIMELINE_EVENT_TYPES: TimelineEventType[] = ['Birth', 'Death', 'Marriage', 'Move', 'Occupation', 'Education', 'Custom'];

@Injectable({ providedIn: 'root' })
export class ApiClient {
  private base = environment.apiBase;
  constructor(private http: HttpClient) {}

  // Trees
  getTrees() { return this.http.get<Tree[]>(`${this.base}/trees`); }
  createTree(name: string, description?: string) { return this.http.post<Tree>(`${this.base}/trees`, { name, description }); }
  updateTree(id: string, name: string, description?: string) { return this.http.put<Tree>(`${this.base}/trees/${id}`, { name, description }); }
  deleteTree(id: string) { return this.http.delete<void>(`${this.base}/trees/${id}`); }

  // Persons
  getPersonsByTree(treeId: string, search?: string) {
    let params = new HttpParams();
    if (search) params = params.set('search', search);
    return this.http.get<Person[]>(`${this.base}/trees/${treeId}/persons`, { params });
  }
  getPerson(id: string) { return this.http.get<Person>(`${this.base}/persons/${id}`); }
  getPersonRelations(id: string) { return this.http.get<PersonRelation[]>(`${this.base}/persons/${id}/relations`); }
  createPerson(treeId: string, body: Partial<Person>) { return this.http.post<Person>(`${this.base}/trees/${treeId}/persons`, body); }
  updatePerson(id: string, body: Partial<Person>) { return this.http.put<Person>(`${this.base}/persons/${id}`, body); }
  deletePerson(id: string) { return this.http.delete<void>(`${this.base}/persons/${id}`); }

  // Relationships
  getRelationships(treeId: string) { return this.http.get<Relationship[]>(`${this.base}/trees/${treeId}/relationships`); }
  createRelationship(treeId: string, body: Partial<Relationship>) { return this.http.post<Relationship>(`${this.base}/trees/${treeId}/relationships`, body); }
  deleteRelationship(treeId: string, id: string) { return this.http.delete<void>(`${this.base}/trees/${treeId}/relationships/${id}`); }

  // Timeline
  getTimeline(personId: string) { return this.http.get<TimelineEvent[]>(`${this.base}/persons/${personId}/timeline`); }
  addTimelineEvent(personId: string, body: Partial<TimelineEvent>) { return this.http.post<TimelineEvent>(`${this.base}/persons/${personId}/timeline`, body); }
  updateTimelineEvent(personId: string, id: string, body: Partial<TimelineEvent>) { return this.http.put<TimelineEvent>(`${this.base}/persons/${personId}/timeline/${id}`, body); }
  deleteTimelineEvent(personId: string, id: string) { return this.http.delete<void>(`${this.base}/persons/${personId}/timeline/${id}`); }

  // Import
  previewImport(treeId: string, text: string) { return this.http.post<ImportReport>(`${this.base}/trees/${treeId}/import/preview`, { text }); }
  commitImport(treeId: string, text: string) { return this.http.post<ImportReport>(`${this.base}/trees/${treeId}/import/commit`, { text }); }
}
