using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Qseng.Application.Abstractions;
using Qseng.Application.Common;
using Qseng.Application.Persons.CreatePerson;
using Qseng.Domain.Enums;
using Qseng.Domain.ValueObjects;

namespace Qseng.Application.Persons.UpdatePerson;

public record UpdatePersonCommand(
    Guid Id,
    string FirstName, string LastName, string? MaidenName,
    Sex Sex, string? Notes,
    PartialDate? Birth, PartialDate? Death,
    string? BirthPlace, string? DeathPlace,
    string? CauseOfDeath)
    : IRequest<Result<PersonDto>>;

public class UpdatePersonValidator : AbstractValidator<UpdatePersonCommand>
{
    public UpdatePersonValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().MaximumLength(200);
        RuleFor(x => x.LastName).NotEmpty().MaximumLength(200);
    }
}

public class UpdatePersonHandler : IRequestHandler<UpdatePersonCommand, Result<PersonDto>>
{
    private readonly IQsengDbContext _db;
    private readonly ICurrentUser _currentUser;

    public UpdatePersonHandler(IQsengDbContext db, ICurrentUser currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<Result<PersonDto>> Handle(UpdatePersonCommand cmd, CancellationToken ct)
    {
        var person = await _db.Persons.FirstOrDefaultAsync(p => p.Id == cmd.Id, ct);
        if (person is null) return Result<PersonDto>.NotFound("Person not found.");

        var tree = await _db.Trees.FindAsync([person.TreeId], ct);
        if (tree is null || tree.OwnerId != _currentUser.UserId) return Result<PersonDto>.Fail("Forbidden.", 403);

        person.FirstName = cmd.FirstName; person.LastName = cmd.LastName;
        person.MaidenName = cmd.MaidenName; person.Sex = cmd.Sex; person.Notes = cmd.Notes;
        person.Birth = cmd.Birth; person.Death = cmd.Death;
        person.BirthPlace = cmd.BirthPlace; person.DeathPlace = cmd.DeathPlace;
        person.CauseOfDeath = cmd.CauseOfDeath;
        person.UpdatedAt = DateTime.UtcNow;

        // Rebuild auto-generated birth/death events to reflect updated dates.
        var autoEvents = await _db.TimelineEvents
            .Where(t => t.PersonId == cmd.Id && t.IsAutoGenerated &&
                (t.Type == TimelineEventType.Birth || t.Type == TimelineEventType.Death))
            .ToListAsync(ct);
        _db.TimelineEvents.RemoveRange(autoEvents);
        CreatePersonHandler.AddBirthDeathEvents(_db, person);

        await _db.SaveChangesAsync(ct);
        return Result<PersonDto>.Ok(CreatePersonHandler.ToDto(person));
    }
}
