// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qseng.Infrastructure.Persistence;

#nullable disable

namespace Qseng.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqliteQsengDbContext))]
    [Migration("20260914142422_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Qseng.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.HasIndex("UserId");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_person_avatar")
                        .HasFilter("\"IsAvatar\" = 1");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("CauseOfDeath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeathPlace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaidenName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("TreeId");

                    b.HasIndex("TreeId", "LastName", "FirstName");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FromPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ToPersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("FromPersonId");

                    b.HasIndex("ToPersonId");

                    b.HasIndex("TreeId", "FromPersonId");

                    b.HasIndex("TreeId", "ToPersonId");

                    b.HasIndex("TreeId", "FromPersonId", "ToPersonId", "Type")
                        .IsUnique();

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.SiteSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegistrationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Qseng.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRelationshipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartSortKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceRelationshipId");

                    b.HasIndex("PersonId", "StartSortKey")
                        .HasDatabaseName("ix_timeline_events_person_sort");

                    b.ToTable("timeline_events", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("trees", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("de");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Qseng.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.Tree", null)
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qseng.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Media", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Person", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.Tree", null)
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "Birth", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Approx")
                                .HasColumnType("INTEGER")
                                .HasColumnName("birth_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("birth_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("birth_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("birth_year");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "Death", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Approx")
                                .HasColumnType("INTEGER")
                                .HasColumnName("death_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("death_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("death_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("death_year");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Birth");

                    b.Navigation("Death");
                });

            modelBuilder.Entity("Qseng.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("FromPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qseng.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("ToPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qseng.Domain.Entities.Tree", null)
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qseng.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.Person", null)
                        .WithMany("Timeline")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Qseng.Domain.Entities.Relationship", null)
                        .WithMany()
                        .HasForeignKey("SourceRelationshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "End", b1 =>
                        {
                            b1.Property<Guid>("TimelineEventId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Approx")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_year");

                            b1.HasKey("TimelineEventId");

                            b1.ToTable("timeline_events");

                            b1.WithOwner()
                                .HasForeignKey("TimelineEventId");
                        });

                    b.OwnsOne("Qseng.Domain.ValueObjects.PartialDate", "Start", b1 =>
                        {
                            b1.Property<Guid>("TimelineEventId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Approx")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_approx");

                            b1.Property<int?>("Day")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_day");

                            b1.Property<int?>("Month")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_month");

                            b1.Property<int?>("Year")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_year");

                            b1.HasKey("TimelineEventId");

                            b1.ToTable("timeline_events");

                            b1.WithOwner()
                                .HasForeignKey("TimelineEventId");
                        });

                    b.Navigation("End");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Tree", b =>
                {
                    b.HasOne("Qseng.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qseng.Domain.Entities.Person", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
